// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: api/control.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Discovery_GetCapabilities_FullMethodName = "/fatima.opm.v2.Discovery/GetCapabilities"
)

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryClient interface {
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
}

type discoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryClient(cc grpc.ClientConnInterface) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, Discovery_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServer is the server API for Discovery service.
// All implementations must embed UnimplementedDiscoveryServer
// for forward compatibility.
type DiscoveryServer interface {
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	mustEmbedUnimplementedDiscoveryServer()
}

// UnimplementedDiscoveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServer struct{}

func (UnimplementedDiscoveryServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedDiscoveryServer) mustEmbedUnimplementedDiscoveryServer() {}
func (UnimplementedDiscoveryServer) testEmbeddedByValue()                   {}

// UnsafeDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServer will
// result in compilation errors.
type UnsafeDiscoveryServer interface {
	mustEmbedUnimplementedDiscoveryServer()
}

func RegisterDiscoveryServer(s grpc.ServiceRegistrar, srv DiscoveryServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Discovery_ServiceDesc, srv)
}

func _Discovery_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Discovery_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Discovery_ServiceDesc is the grpc.ServiceDesc for Discovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Discovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _Discovery_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/control.proto",
}

const (
	Identity_Login_FullMethodName    = "/fatima.opm.v2.Identity/Login"
	Identity_Validate_FullMethodName = "/fatima.opm.v2.Identity/Validate"
)

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Session, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*Session, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Identity_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Identity_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
// All implementations must embed UnimplementedIdentityServer
// for forward compatibility.
type IdentityServer interface {
	Login(context.Context, *LoginRequest) (*Session, error)
	Validate(context.Context, *ValidateRequest) (*Session, error)
	mustEmbedUnimplementedIdentityServer()
}

// UnimplementedIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServer struct{}

func (UnimplementedIdentityServer) Login(context.Context, *LoginRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIdentityServer) Validate(context.Context, *ValidateRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedIdentityServer) mustEmbedUnimplementedIdentityServer() {}
func (UnimplementedIdentityServer) testEmbeddedByValue()                  {}

// UnsafeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServer will
// result in compilation errors.
type UnsafeIdentityServer interface {
	mustEmbedUnimplementedIdentityServer()
}

func RegisterIdentityServer(s grpc.ServiceRegistrar, srv IdentityServer) {
	// If the following call pancis, it indicates UnimplementedIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identity_ServiceDesc, srv)
}

func _Identity_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Identity_ServiceDesc is the grpc.ServiceDesc for Identity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Identity_Login_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Identity_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/control.proto",
}

const (
	Artifacts_Upload_FullMethodName = "/fatima.opm.v2.Artifacts/Upload"
	Artifacts_List_FullMethodName   = "/fatima.opm.v2.Artifacts/List"
	Artifacts_Get_FullMethodName    = "/fatima.opm.v2.Artifacts/Get"
)

// ArtifactsClient is the client API for Artifacts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactsClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, Artifact], error)
	List(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*ArtifactList, error)
	Get(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*Artifact, error)
}

type artifactsClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactsClient(cc grpc.ClientConnInterface) ArtifactsClient {
	return &artifactsClient{cc}
}

func (c *artifactsClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, Artifact], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Artifacts_ServiceDesc.Streams[0], Artifacts_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, Artifact]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Artifacts_UploadClient = grpc.ClientStreamingClient[UploadChunk, Artifact]

func (c *artifactsClient) List(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*ArtifactList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactList)
	err := c.cc.Invoke(ctx, Artifacts_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactsClient) Get(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, Artifacts_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactsServer is the server API for Artifacts service.
// All implementations must embed UnimplementedArtifactsServer
// for forward compatibility.
type ArtifactsServer interface {
	Upload(grpc.ClientStreamingServer[UploadChunk, Artifact]) error
	List(context.Context, *ArtifactQuery) (*ArtifactList, error)
	Get(context.Context, *ArtifactQuery) (*Artifact, error)
	mustEmbedUnimplementedArtifactsServer()
}

// UnimplementedArtifactsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactsServer struct{}

func (UnimplementedArtifactsServer) Upload(grpc.ClientStreamingServer[UploadChunk, Artifact]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedArtifactsServer) List(context.Context, *ArtifactQuery) (*ArtifactList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedArtifactsServer) Get(context.Context, *ArtifactQuery) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedArtifactsServer) mustEmbedUnimplementedArtifactsServer() {}
func (UnimplementedArtifactsServer) testEmbeddedByValue()                   {}

// UnsafeArtifactsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactsServer will
// result in compilation errors.
type UnsafeArtifactsServer interface {
	mustEmbedUnimplementedArtifactsServer()
}

func RegisterArtifactsServer(s grpc.ServiceRegistrar, srv ArtifactsServer) {
	// If the following call pancis, it indicates UnimplementedArtifactsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Artifacts_ServiceDesc, srv)
}

func _Artifacts_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArtifactsServer).Upload(&grpc.GenericServerStream[UploadChunk, Artifact]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Artifacts_UploadServer = grpc.ClientStreamingServer[UploadChunk, Artifact]

func _Artifacts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artifacts_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactsServer).List(ctx, req.(*ArtifactQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artifacts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artifacts_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactsServer).Get(ctx, req.(*ArtifactQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Artifacts_ServiceDesc is the grpc.ServiceDesc for Artifacts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Artifacts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.Artifacts",
	HandlerType: (*ArtifactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Artifacts_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Artifacts_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Artifacts_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/control.proto",
}

const (
	DeploymentManagement_Open_FullMethodName      = "/fatima.opm.v2.DeploymentManagement/Open"
	DeploymentManagement_Heartbeat_FullMethodName = "/fatima.opm.v2.DeploymentManagement/Heartbeat"
	DeploymentManagement_Detach_FullMethodName    = "/fatima.opm.v2.DeploymentManagement/Detach"
)

// DeploymentManagementClient is the client API for DeploymentManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentManagementClient interface {
	Open(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ManagementSession, error)
	Heartbeat(ctx context.Context, in *ManagementCredential, opts ...grpc.CallOption) (*ManagementSession, error)
	Detach(ctx context.Context, in *ManagementCredential, opts ...grpc.CallOption) (*ManagementSession, error)
}

type deploymentManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentManagementClient(cc grpc.ClientConnInterface) DeploymentManagementClient {
	return &deploymentManagementClient{cc}
}

func (c *deploymentManagementClient) Open(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ManagementSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementSession)
	err := c.cc.Invoke(ctx, DeploymentManagement_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentManagementClient) Heartbeat(ctx context.Context, in *ManagementCredential, opts ...grpc.CallOption) (*ManagementSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementSession)
	err := c.cc.Invoke(ctx, DeploymentManagement_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentManagementClient) Detach(ctx context.Context, in *ManagementCredential, opts ...grpc.CallOption) (*ManagementSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementSession)
	err := c.cc.Invoke(ctx, DeploymentManagement_Detach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentManagementServer is the server API for DeploymentManagement service.
// All implementations must embed UnimplementedDeploymentManagementServer
// for forward compatibility.
type DeploymentManagementServer interface {
	Open(context.Context, *Empty) (*ManagementSession, error)
	Heartbeat(context.Context, *ManagementCredential) (*ManagementSession, error)
	Detach(context.Context, *ManagementCredential) (*ManagementSession, error)
	mustEmbedUnimplementedDeploymentManagementServer()
}

// UnimplementedDeploymentManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentManagementServer struct{}

func (UnimplementedDeploymentManagementServer) Open(context.Context, *Empty) (*ManagementSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedDeploymentManagementServer) Heartbeat(context.Context, *ManagementCredential) (*ManagementSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDeploymentManagementServer) Detach(context.Context, *ManagementCredential) (*ManagementSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detach not implemented")
}
func (UnimplementedDeploymentManagementServer) mustEmbedUnimplementedDeploymentManagementServer() {}
func (UnimplementedDeploymentManagementServer) testEmbeddedByValue()                              {}

// UnsafeDeploymentManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentManagementServer will
// result in compilation errors.
type UnsafeDeploymentManagementServer interface {
	mustEmbedUnimplementedDeploymentManagementServer()
}

func RegisterDeploymentManagementServer(s grpc.ServiceRegistrar, srv DeploymentManagementServer) {
	// If the following call pancis, it indicates UnimplementedDeploymentManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentManagement_ServiceDesc, srv)
}

func _DeploymentManagement_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentManagementServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentManagement_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentManagementServer).Open(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentManagement_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagementCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentManagementServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentManagement_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentManagementServer).Heartbeat(ctx, req.(*ManagementCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentManagement_Detach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagementCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentManagementServer).Detach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentManagement_Detach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentManagementServer).Detach(ctx, req.(*ManagementCredential))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentManagement_ServiceDesc is the grpc.ServiceDesc for DeploymentManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.DeploymentManagement",
	HandlerType: (*DeploymentManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _DeploymentManagement_Open_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DeploymentManagement_Heartbeat_Handler,
		},
		{
			MethodName: "Detach",
			Handler:    _DeploymentManagement_Detach_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/control.proto",
}

const (
	Deployments_Targets_FullMethodName = "/fatima.opm.v2.Deployments/Targets"
	Deployments_Create_FullMethodName  = "/fatima.opm.v2.Deployments/Create"
	Deployments_List_FullMethodName    = "/fatima.opm.v2.Deployments/List"
	Deployments_Get_FullMethodName     = "/fatima.opm.v2.Deployments/Get"
	Deployments_Act_FullMethodName     = "/fatima.opm.v2.Deployments/Act"
	Deployments_Watch_FullMethodName   = "/fatima.opm.v2.Deployments/Watch"
)

// DeploymentsClient is the client API for Deployments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentsClient interface {
	Targets(ctx context.Context, in *TargetQuery, opts ...grpc.CallOption) (*TargetList, error)
	Create(ctx context.Context, in *CreateRollout, opts ...grpc.CallOption) (*Rollout, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RolloutList, error)
	Get(ctx context.Context, in *RolloutQuery, opts ...grpc.CallOption) (*Rollout, error)
	Act(ctx context.Context, in *RolloutAction, opts ...grpc.CallOption) (*Rollout, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Rollout], error)
}

type deploymentsClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentsClient(cc grpc.ClientConnInterface) DeploymentsClient {
	return &deploymentsClient{cc}
}

func (c *deploymentsClient) Targets(ctx context.Context, in *TargetQuery, opts ...grpc.CallOption) (*TargetList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetList)
	err := c.cc.Invoke(ctx, Deployments_Targets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) Create(ctx context.Context, in *CreateRollout, opts ...grpc.CallOption) (*Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rollout)
	err := c.cc.Invoke(ctx, Deployments_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RolloutList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloutList)
	err := c.cc.Invoke(ctx, Deployments_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) Get(ctx context.Context, in *RolloutQuery, opts ...grpc.CallOption) (*Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rollout)
	err := c.cc.Invoke(ctx, Deployments_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) Act(ctx context.Context, in *RolloutAction, opts ...grpc.CallOption) (*Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rollout)
	err := c.cc.Invoke(ctx, Deployments_Act_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Rollout], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Deployments_ServiceDesc.Streams[0], Deployments_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Rollout]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Deployments_WatchClient = grpc.ServerStreamingClient[Rollout]

// DeploymentsServer is the server API for Deployments service.
// All implementations must embed UnimplementedDeploymentsServer
// for forward compatibility.
type DeploymentsServer interface {
	Targets(context.Context, *TargetQuery) (*TargetList, error)
	Create(context.Context, *CreateRollout) (*Rollout, error)
	List(context.Context, *Empty) (*RolloutList, error)
	Get(context.Context, *RolloutQuery) (*Rollout, error)
	Act(context.Context, *RolloutAction) (*Rollout, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[Rollout]) error
	mustEmbedUnimplementedDeploymentsServer()
}

// UnimplementedDeploymentsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentsServer struct{}

func (UnimplementedDeploymentsServer) Targets(context.Context, *TargetQuery) (*TargetList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Targets not implemented")
}
func (UnimplementedDeploymentsServer) Create(context.Context, *CreateRollout) (*Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDeploymentsServer) List(context.Context, *Empty) (*RolloutList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDeploymentsServer) Get(context.Context, *RolloutQuery) (*Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDeploymentsServer) Act(context.Context, *RolloutAction) (*Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Act not implemented")
}
func (UnimplementedDeploymentsServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Rollout]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedDeploymentsServer) mustEmbedUnimplementedDeploymentsServer() {}
func (UnimplementedDeploymentsServer) testEmbeddedByValue()                     {}

// UnsafeDeploymentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentsServer will
// result in compilation errors.
type UnsafeDeploymentsServer interface {
	mustEmbedUnimplementedDeploymentsServer()
}

func RegisterDeploymentsServer(s grpc.ServiceRegistrar, srv DeploymentsServer) {
	// If the following call pancis, it indicates UnimplementedDeploymentsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Deployments_ServiceDesc, srv)
}

func _Deployments_Targets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).Targets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deployments_Targets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).Targets(ctx, req.(*TargetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRollout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deployments_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).Create(ctx, req.(*CreateRollout))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deployments_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deployments_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).Get(ctx, req.(*RolloutQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deployments_Act_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServer).Act(ctx, req.(*RolloutAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deployments_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeploymentsServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Rollout]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Deployments_WatchServer = grpc.ServerStreamingServer[Rollout]

// Deployments_ServiceDesc is the grpc.ServiceDesc for Deployments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deployments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.Deployments",
	HandlerType: (*DeploymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Targets",
			Handler:    _Deployments_Targets_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Deployments_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Deployments_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Deployments_Get_Handler,
		},
		{
			MethodName: "Act",
			Handler:    _Deployments_Act_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Deployments_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/control.proto",
}

const (
	PackageDeployment_Cancel_FullMethodName = "/fatima.opm.v2.PackageDeployment/Cancel"
	PackageDeployment_Stage_FullMethodName  = "/fatima.opm.v2.PackageDeployment/Stage"
	PackageDeployment_Start_FullMethodName  = "/fatima.opm.v2.PackageDeployment/Start"
	PackageDeployment_Get_FullMethodName    = "/fatima.opm.v2.PackageDeployment/Get"
	PackageDeployment_Watch_FullMethodName  = "/fatima.opm.v2.PackageDeployment/Watch"
)

// PackageDeploymentClient is the client API for PackageDeployment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackageDeploymentClient interface {
	Cancel(ctx context.Context, in *OperationSpec, opts ...grpc.CallOption) (*Operation, error)
	Stage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StageChunk, Operation], error)
	Start(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*Operation, error)
	Get(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*Operation, error)
	Watch(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Operation], error)
}

type packageDeploymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageDeploymentClient(cc grpc.ClientConnInterface) PackageDeploymentClient {
	return &packageDeploymentClient{cc}
}

func (c *packageDeploymentClient) Cancel(ctx context.Context, in *OperationSpec, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, PackageDeployment_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageDeploymentClient) Stage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StageChunk, Operation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageDeployment_ServiceDesc.Streams[0], PackageDeployment_Stage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StageChunk, Operation]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageDeployment_StageClient = grpc.ClientStreamingClient[StageChunk, Operation]

func (c *packageDeploymentClient) Start(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, PackageDeployment_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageDeploymentClient) Get(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, PackageDeployment_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageDeploymentClient) Watch(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Operation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageDeployment_ServiceDesc.Streams[1], PackageDeployment_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OperationQuery, Operation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageDeployment_WatchClient = grpc.ServerStreamingClient[Operation]

// PackageDeploymentServer is the server API for PackageDeployment service.
// All implementations must embed UnimplementedPackageDeploymentServer
// for forward compatibility.
type PackageDeploymentServer interface {
	Cancel(context.Context, *OperationSpec) (*Operation, error)
	Stage(grpc.ClientStreamingServer[StageChunk, Operation]) error
	Start(context.Context, *OperationQuery) (*Operation, error)
	Get(context.Context, *OperationQuery) (*Operation, error)
	Watch(*OperationQuery, grpc.ServerStreamingServer[Operation]) error
	mustEmbedUnimplementedPackageDeploymentServer()
}

// UnimplementedPackageDeploymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackageDeploymentServer struct{}

func (UnimplementedPackageDeploymentServer) Cancel(context.Context, *OperationSpec) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedPackageDeploymentServer) Stage(grpc.ClientStreamingServer[StageChunk, Operation]) error {
	return status.Errorf(codes.Unimplemented, "method Stage not implemented")
}
func (UnimplementedPackageDeploymentServer) Start(context.Context, *OperationQuery) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPackageDeploymentServer) Get(context.Context, *OperationQuery) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPackageDeploymentServer) Watch(*OperationQuery, grpc.ServerStreamingServer[Operation]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedPackageDeploymentServer) mustEmbedUnimplementedPackageDeploymentServer() {}
func (UnimplementedPackageDeploymentServer) testEmbeddedByValue()                           {}

// UnsafePackageDeploymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageDeploymentServer will
// result in compilation errors.
type UnsafePackageDeploymentServer interface {
	mustEmbedUnimplementedPackageDeploymentServer()
}

func RegisterPackageDeploymentServer(s grpc.ServiceRegistrar, srv PackageDeploymentServer) {
	// If the following call pancis, it indicates UnimplementedPackageDeploymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackageDeployment_ServiceDesc, srv)
}

func _PackageDeployment_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageDeploymentServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageDeployment_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageDeploymentServer).Cancel(ctx, req.(*OperationSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageDeployment_Stage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PackageDeploymentServer).Stage(&grpc.GenericServerStream[StageChunk, Operation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageDeployment_StageServer = grpc.ClientStreamingServer[StageChunk, Operation]

func _PackageDeployment_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageDeploymentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageDeployment_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageDeploymentServer).Start(ctx, req.(*OperationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageDeployment_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageDeploymentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageDeployment_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageDeploymentServer).Get(ctx, req.(*OperationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageDeployment_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OperationQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageDeploymentServer).Watch(m, &grpc.GenericServerStream[OperationQuery, Operation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageDeployment_WatchServer = grpc.ServerStreamingServer[Operation]

// PackageDeployment_ServiceDesc is the grpc.ServiceDesc for PackageDeployment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackageDeployment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.PackageDeployment",
	HandlerType: (*PackageDeploymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cancel",
			Handler:    _PackageDeployment_Cancel_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PackageDeployment_Start_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PackageDeployment_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stage",
			Handler:       _PackageDeployment_Stage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _PackageDeployment_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/control.proto",
}
