// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.36.0
// source: api/control.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{0}
}

type Capabilities struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Server             string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ApiVersion         uint32                 `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Features           []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	PackageId          string                 `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Platform           string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	InstanceId         string                 `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ArtifactTtlSeconds int64                  `protobuf:"varint,7,opt,name=artifact_ttl_seconds,json=artifactTtlSeconds,proto3" json:"artifact_ttl_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_api_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{1}
}

func (x *Capabilities) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Capabilities) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Capabilities) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Capabilities) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Capabilities) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Capabilities) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Capabilities) GetArtifactTtlSeconds() int64 {
	if x != nil {
		return x.ArtifactTtlSeconds
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Session) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	PackageId     string                 `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ValidateRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ValidateRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Process       string                 `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Platforms     []string               `protobuf:"bytes,6,rep,name=platforms,proto3" json:"platforms,omitempty"`
	BuildJson     string                 `protobuf:"bytes,7,opt,name=build_json,json=buildJson,proto3" json:"build_json,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,8,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	UploadedAt    int64                  `protobuf:"varint,9,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Expired       bool                   `protobuf:"varint,11,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_api_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Artifact) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Artifact) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *Artifact) GetBuildJson() string {
	if x != nil {
		return x.BuildJson
	}
	return ""
}

func (x *Artifact) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *Artifact) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

func (x *Artifact) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Artifact) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

type UploadHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadHeader) Reset() {
	*x = UploadHeader{}
	mi := &file_api_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadHeader) ProtoMessage() {}

func (x *UploadHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadHeader.ProtoReflect.Descriptor instead.
func (*UploadHeader) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{6}
}

func (x *UploadHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UploadHeader) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadHeader) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *UploadHeader          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_api_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{7}
}

func (x *UploadChunk) GetHeader() *UploadHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Process       string                 `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactQuery) Reset() {
	*x = ArtifactQuery{}
	mi := &file_api_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactQuery) ProtoMessage() {}

func (x *ArtifactQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactQuery.ProtoReflect.Descriptor instead.
func (*ArtifactQuery) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{8}
}

func (x *ArtifactQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtifactQuery) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

type ArtifactList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*Artifact            `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactList) Reset() {
	*x = ArtifactList{}
	mi := &file_api_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactList) ProtoMessage() {}

func (x *ArtifactList) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactList.ProtoReflect.Descriptor instead.
func (*ArtifactList) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactList) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type Target struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PackageId       string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Group           string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Endpoint        string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Platform        string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Supported       bool                   `protobuf:"varint,5,opt,name=supported,proto3" json:"supported,omitempty"`
	Reason          string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Legacy          bool                   `protobuf:"varint,7,opt,name=legacy,proto3" json:"legacy,omitempty"`
	CancelSupported bool                   `protobuf:"varint,8,opt,name=cancel_supported,json=cancelSupported,proto3" json:"cancel_supported,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_api_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{10}
}

func (x *Target) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Target) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Target) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Target) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Target) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *Target) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Target) GetLegacy() bool {
	if x != nil {
		return x.Legacy
	}
	return false
}

func (x *Target) GetCancelSupported() bool {
	if x != nil {
		return x.CancelSupported
	}
	return false
}

type TargetQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetQuery) Reset() {
	*x = TargetQuery{}
	mi := &file_api_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetQuery) ProtoMessage() {}

func (x *TargetQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetQuery.ProtoReflect.Descriptor instead.
func (*TargetQuery) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{11}
}

func (x *TargetQuery) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type TargetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetList) Reset() {
	*x = TargetList{}
	mi := &file_api_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetList) ProtoMessage() {}

func (x *TargetList) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetList.ProtoReflect.Descriptor instead.
func (*TargetList) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{12}
}

func (x *TargetList) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type CreateRollout struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ArtifactId     string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Group          string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	PackageIds     []string               `protobuf:"bytes,4,rep,name=package_ids,json=packageIds,proto3" json:"package_ids,omitempty"`
	FirstPackageId string                 `protobuf:"bytes,5,opt,name=first_package_id,json=firstPackageId,proto3" json:"first_package_id,omitempty"`
	Management     *ManagementCredential  `protobuf:"bytes,6,opt,name=management,proto3" json:"management,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRollout) Reset() {
	*x = CreateRollout{}
	mi := &file_api_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRollout) ProtoMessage() {}

func (x *CreateRollout) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRollout.ProtoReflect.Descriptor instead.
func (*CreateRollout) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRollout) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateRollout) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *CreateRollout) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreateRollout) GetPackageIds() []string {
	if x != nil {
		return x.PackageIds
	}
	return nil
}

func (x *CreateRollout) GetFirstPackageId() string {
	if x != nil {
		return x.FirstPackageId
	}
	return ""
}

func (x *CreateRollout) GetManagement() *ManagementCredential {
	if x != nil {
		return x.Management
	}
	return nil
}

type RolloutQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutQuery) Reset() {
	*x = RolloutQuery{}
	mi := &file_api_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutQuery) ProtoMessage() {}

func (x *RolloutQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutQuery.ProtoReflect.Descriptor instead.
func (*RolloutQuery) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{14}
}

func (x *RolloutQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RolloutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rollouts      []*Rollout             `protobuf:"bytes,1,rep,name=rollouts,proto3" json:"rollouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutList) Reset() {
	*x = RolloutList{}
	mi := &file_api_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutList) ProtoMessage() {}

func (x *RolloutList) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutList.ProtoReflect.Descriptor instead.
func (*RolloutList) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{15}
}

func (x *RolloutList) GetRollouts() []*Rollout {
	if x != nil {
		return x.Rollouts
	}
	return nil
}

type RolloutAction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action           string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RolloutAction) Reset() {
	*x = RolloutAction{}
	mi := &file_api_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutAction) ProtoMessage() {}

func (x *RolloutAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutAction.ProtoReflect.Descriptor instead.
func (*RolloutAction) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{16}
}

func (x *RolloutAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RolloutAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RolloutAction) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AfterRevision uint64                 `protobuf:"varint,2,opt,name=after_revision,json=afterRevision,proto3" json:"after_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{17}
}

func (x *WatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchRequest) GetAfterRevision() uint64 {
	if x != nil {
		return x.AfterRevision
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	At            int64                  `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Current       int64                  `protobuf:"varint,6,opt,name=current,proto3" json:"current,omitempty"`
	Total         int64                  `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{18}
}

func (x *Event) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Event) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Event) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Event) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Event) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactId       string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Sha256           string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Process          string                 `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	PackageId        string                 `protobuf:"bytes,5,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	State            string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Events           []*Event               `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	Error            string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt        int64                  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       int64                  `protobuf:"varint,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	RevisionPath     string                 `protobuf:"bytes,11,opt,name=revision_path,json=revisionPath,proto3" json:"revision_path,omitempty"`
	PreviousRevision string                 `protobuf:"bytes,12,opt,name=previous_revision,json=previousRevision,proto3" json:"previous_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{19}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Operation) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Operation) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *Operation) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Operation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Operation) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Operation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Operation) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Operation) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *Operation) GetRevisionPath() string {
	if x != nil {
		return x.RevisionPath
	}
	return ""
}

func (x *Operation) GetPreviousRevision() string {
	if x != nil {
		return x.PreviousRevision
	}
	return ""
}

type TargetRun struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Target           *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Operation        *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	SentBytes        int64                  `protobuf:"varint,3,opt,name=sent_bytes,json=sentBytes,proto3" json:"sent_bytes,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	PreviousAttempts []*Operation           `protobuf:"bytes,5,rep,name=previous_attempts,json=previousAttempts,proto3" json:"previous_attempts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetRun) Reset() {
	*x = TargetRun{}
	mi := &file_api_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRun) ProtoMessage() {}

func (x *TargetRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRun.ProtoReflect.Descriptor instead.
func (*TargetRun) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{20}
}

func (x *TargetRun) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TargetRun) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *TargetRun) GetSentBytes() int64 {
	if x != nil {
		return x.SentBytes
	}
	return 0
}

func (x *TargetRun) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TargetRun) GetPreviousAttempts() []*Operation {
	if x != nil {
		return x.PreviousAttempts
	}
	return nil
}

type Rollout struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Artifact            *Artifact              `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Group               string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Targets             []*TargetRun           `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	State               string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedBy           string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Revision            uint64                 `protobuf:"varint,8,opt,name=revision,proto3" json:"revision,omitempty"`
	Message             string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	RemainingApproved   bool                   `protobuf:"varint,10,opt,name=remaining_approved,json=remainingApproved,proto3" json:"remaining_approved,omitempty"`
	CancelRequested     bool                   `protobuf:"varint,11,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	ManagementSessionId string                 `protobuf:"bytes,12,opt,name=management_session_id,json=managementSessionId,proto3" json:"management_session_id,omitempty"`
	EndReason           string                 `protobuf:"bytes,13,opt,name=end_reason,json=endReason,proto3" json:"end_reason,omitempty"`
	LastCheckedAt       int64                  `protobuf:"varint,14,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	NextCheckAt         int64                  `protobuf:"varint,15,opt,name=next_check_at,json=nextCheckAt,proto3" json:"next_check_at,omitempty"`
	BlocksDeployment    bool                   `protobuf:"varint,16,opt,name=blocks_deployment,json=blocksDeployment,proto3" json:"blocks_deployment,omitempty"`
	NextTargetStartAt   int64                  `protobuf:"varint,17,opt,name=next_target_start_at,json=nextTargetStartAt,proto3" json:"next_target_start_at,omitempty"` // Unix milliseconds; zero when no inter-target wait is scheduled.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Rollout) Reset() {
	*x = Rollout{}
	mi := &file_api_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rollout) ProtoMessage() {}

func (x *Rollout) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rollout.ProtoReflect.Descriptor instead.
func (*Rollout) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{21}
}

func (x *Rollout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rollout) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *Rollout) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Rollout) GetTargets() []*TargetRun {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Rollout) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Rollout) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Rollout) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Rollout) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Rollout) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Rollout) GetRemainingApproved() bool {
	if x != nil {
		return x.RemainingApproved
	}
	return false
}

func (x *Rollout) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

func (x *Rollout) GetManagementSessionId() string {
	if x != nil {
		return x.ManagementSessionId
	}
	return ""
}

func (x *Rollout) GetEndReason() string {
	if x != nil {
		return x.EndReason
	}
	return ""
}

func (x *Rollout) GetLastCheckedAt() int64 {
	if x != nil {
		return x.LastCheckedAt
	}
	return 0
}

func (x *Rollout) GetNextCheckAt() int64 {
	if x != nil {
		return x.NextCheckAt
	}
	return 0
}

func (x *Rollout) GetBlocksDeployment() bool {
	if x != nil {
		return x.BlocksDeployment
	}
	return false
}

func (x *Rollout) GetNextTargetStartAt() int64 {
	if x != nil {
		return x.NextTargetStartAt
	}
	return 0
}

// Management belongs to the creating CLI, never to a Watch stream. Times are Unix milliseconds.
type ManagementCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementCredential) Reset() {
	*x = ManagementCredential{}
	mi := &file_api_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementCredential) ProtoMessage() {}

func (x *ManagementCredential) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementCredential.ProtoReflect.Descriptor instead.
func (*ManagementCredential) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{22}
}

func (x *ManagementCredential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagementCredential) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ManagementSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	LastSeenAt    int64                  `protobuf:"varint,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RolloutId     string                 `protobuf:"bytes,5,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementSession) Reset() {
	*x = ManagementSession{}
	mi := &file_api_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementSession) ProtoMessage() {}

func (x *ManagementSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementSession.ProtoReflect.Descriptor instead.
func (*ManagementSession) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{23}
}

func (x *ManagementSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagementSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ManagementSession) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *ManagementSession) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ManagementSession) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *ManagementSession) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Returned as gRPC status details on a conflicting Create/Act; no string parsing needed.
type RolloutConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Process       string                 `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutConflict) Reset() {
	*x = RolloutConflict{}
	mi := &file_api_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutConflict) ProtoMessage() {}

func (x *RolloutConflict) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutConflict.ProtoReflect.Descriptor instead.
func (*RolloutConflict) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{24}
}

func (x *RolloutConflict) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *RolloutConflict) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RolloutConflict) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

type OperationSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Process       string                 `protobuf:"bytes,5,opt,name=process,proto3" json:"process,omitempty"`
	PackageId     string                 `protobuf:"bytes,6,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationSpec) Reset() {
	*x = OperationSpec{}
	mi := &file_api_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationSpec) ProtoMessage() {}

func (x *OperationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationSpec.ProtoReflect.Descriptor instead.
func (*OperationSpec) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{25}
}

func (x *OperationSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationSpec) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *OperationSpec) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *OperationSpec) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OperationSpec) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *OperationSpec) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *OperationSpec) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type StageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *OperationSpec         `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageChunk) Reset() {
	*x = StageChunk{}
	mi := &file_api_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageChunk) ProtoMessage() {}

func (x *StageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageChunk.ProtoReflect.Descriptor instead.
func (*StageChunk) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{26}
}

func (x *StageChunk) GetSpec() *OperationSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *StageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OperationQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationQuery) Reset() {
	*x = OperationQuery{}
	mi := &file_api_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationQuery) ProtoMessage() {}

func (x *OperationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationQuery.ProtoReflect.Descriptor instead.
func (*OperationQuery) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{27}
}

func (x *OperationQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_control_proto protoreflect.FileDescriptor

const file_api_control_proto_rawDesc = "" +
	"\n" +
	"\x11api/control.proto\x12\rfatima.opm.v2\"\a\n" +
	"\x05Empty\"\xf1\x01\n" +
	"\fCapabilities\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\rR\n" +
	"apiVersion\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12\x1d\n" +
	"\n" +
	"package_id\x18\x04 \x01(\tR\tpackageId\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x120\n" +
	"\x14artifact_ttl_seconds\x18\a \x01(\x03R\x12artifactTtlSeconds\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"n\n" +
	"\aSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x7f\n" +
	"\x0fValidateRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"package_id\x18\x04 \x01(\tR\tpackageId\"\xb4\x02\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\aprocess\x18\x03 \x01(\tR\aprocess\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1c\n" +
	"\tplatforms\x18\x06 \x03(\tR\tplatforms\x12\x1d\n" +
	"\n" +
	"build_json\x18\a \x01(\tR\tbuildJson\x12\x1f\n" +
	"\vuploaded_by\x18\b \x01(\tR\n" +
	"uploadedBy\x12\x1f\n" +
	"\vuploaded_at\x18\t \x01(\x03R\n" +
	"uploadedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aexpired\x18\v \x01(\bR\aexpired\"u\n" +
	"\fUploadHeader\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"V\n" +
	"\vUploadChunk\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.fatima.opm.v2.UploadHeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"9\n" +
	"\rArtifactQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aprocess\x18\x02 \x01(\tR\aprocess\"E\n" +
	"\fArtifactList\x125\n" +
	"\tartifacts\x18\x01 \x03(\v2\x17.fatima.opm.v2.ArtifactR\tartifacts\"\xee\x01\n" +
	"\x06Target\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1c\n" +
	"\tsupported\x18\x05 \x01(\bR\tsupported\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x16\n" +
	"\x06legacy\x18\a \x01(\bR\x06legacy\x12)\n" +
	"\x10cancel_supported\x18\b \x01(\bR\x0fcancelSupported\"#\n" +
	"\vTargetQuery\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"=\n" +
	"\n" +
	"TargetList\x12/\n" +
	"\atargets\x18\x01 \x03(\v2\x15.fatima.opm.v2.TargetR\atargets\"\xf5\x01\n" +
	"\rCreateRollout\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x1f\n" +
	"\vpackage_ids\x18\x04 \x03(\tR\n" +
	"packageIds\x12(\n" +
	"\x10first_package_id\x18\x05 \x01(\tR\x0efirstPackageId\x12C\n" +
	"\n" +
	"management\x18\x06 \x01(\v2#.fatima.opm.v2.ManagementCredentialR\n" +
	"management\"\x1e\n" +
	"\fRolloutQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\vRolloutList\x122\n" +
	"\brollouts\x18\x01 \x03(\v2\x16.fatima.opm.v2.RolloutR\brollouts\"d\n" +
	"\rRolloutAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\"E\n" +
	"\fWatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eafter_revision\x18\x02 \x01(\x04R\rafterRevision\"\xa9\x01\n" +
	"\x05Event\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x03R\x02at\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05total\x18\a \x01(\x03R\x05total\"\xf9\x02\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x18\n" +
	"\aprocess\x18\x04 \x01(\tR\aprocess\x12\x1d\n" +
	"\n" +
	"package_id\x18\x05 \x01(\tR\tpackageId\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12,\n" +
	"\x06events\x18\a \x03(\v2\x14.fatima.opm.v2.EventR\x06events\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\n" +
	" \x01(\x03R\n" +
	"finishedAt\x12#\n" +
	"\rrevision_path\x18\v \x01(\tR\frevisionPath\x12+\n" +
	"\x11previous_revision\x18\f \x01(\tR\x10previousRevision\"\xf9\x01\n" +
	"\tTargetRun\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.fatima.opm.v2.TargetR\x06target\x126\n" +
	"\toperation\x18\x02 \x01(\v2\x18.fatima.opm.v2.OperationR\toperation\x12\x1d\n" +
	"\n" +
	"sent_bytes\x18\x03 \x01(\x03R\tsentBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12E\n" +
	"\x11previous_attempts\x18\x05 \x03(\v2\x18.fatima.opm.v2.OperationR\x10previousAttempts\"\xf9\x04\n" +
	"\aRollout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\bartifact\x18\x02 \x01(\v2\x17.fatima.opm.v2.ArtifactR\bartifact\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x122\n" +
	"\atargets\x18\x04 \x03(\v2\x18.fatima.opm.v2.TargetRunR\atargets\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\brevision\x18\b \x01(\x04R\brevision\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12-\n" +
	"\x12remaining_approved\x18\n" +
	" \x01(\bR\x11remainingApproved\x12)\n" +
	"\x10cancel_requested\x18\v \x01(\bR\x0fcancelRequested\x122\n" +
	"\x15management_session_id\x18\f \x01(\tR\x13managementSessionId\x12\x1d\n" +
	"\n" +
	"end_reason\x18\r \x01(\tR\tendReason\x12&\n" +
	"\x0flast_checked_at\x18\x0e \x01(\x03R\rlastCheckedAt\x12\"\n" +
	"\rnext_check_at\x18\x0f \x01(\x03R\vnextCheckAt\x12+\n" +
	"\x11blocks_deployment\x18\x10 \x01(\bR\x10blocksDeployment\x12/\n" +
	"\x14next_target_start_at\x18\x11 \x01(\x03R\x11nextTargetStartAt\"<\n" +
	"\x14ManagementCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xaf\x01\n" +
	"\x11ManagementSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12 \n" +
	"\flast_seen_at\x18\x03 \x01(\x03R\n" +
	"lastSeenAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x05 \x01(\tR\trolloutId\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\"`\n" +
	"\x0fRolloutConflict\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aprocess\x18\x03 \x01(\tR\aprocess\"\xc4\x01\n" +
	"\rOperationSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x18\n" +
	"\aprocess\x18\x05 \x01(\tR\aprocess\x12\x1d\n" +
	"\n" +
	"package_id\x18\x06 \x01(\tR\tpackageId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\"R\n" +
	"\n" +
	"StageChunk\x120\n" +
	"\x04spec\x18\x01 \x01(\v2\x1c.fatima.opm.v2.OperationSpecR\x04spec\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\" \n" +
	"\x0eOperationQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2Q\n" +
	"\tDiscovery\x12D\n" +
	"\x0fGetCapabilities\x12\x14.fatima.opm.v2.Empty\x1a\x1b.fatima.opm.v2.Capabilities2\x8c\x01\n" +
	"\bIdentity\x12<\n" +
	"\x05Login\x12\x1b.fatima.opm.v2.LoginRequest\x1a\x16.fatima.opm.v2.Session\x12B\n" +
	"\bValidate\x12\x1e.fatima.opm.v2.ValidateRequest\x1a\x16.fatima.opm.v2.Session2\xcd\x01\n" +
	"\tArtifacts\x12?\n" +
	"\x06Upload\x12\x1a.fatima.opm.v2.UploadChunk\x1a\x17.fatima.opm.v2.Artifact(\x01\x12A\n" +
	"\x04List\x12\x1c.fatima.opm.v2.ArtifactQuery\x1a\x1b.fatima.opm.v2.ArtifactList\x12<\n" +
	"\x03Get\x12\x1c.fatima.opm.v2.ArtifactQuery\x1a\x17.fatima.opm.v2.Artifact2\xfb\x01\n" +
	"\x14DeploymentManagement\x12>\n" +
	"\x04Open\x12\x14.fatima.opm.v2.Empty\x1a .fatima.opm.v2.ManagementSession\x12R\n" +
	"\tHeartbeat\x12#.fatima.opm.v2.ManagementCredential\x1a .fatima.opm.v2.ManagementSession\x12O\n" +
	"\x06Detach\x12#.fatima.opm.v2.ManagementCredential\x1a .fatima.opm.v2.ManagementSession2\x82\x03\n" +
	"\vDeployments\x12@\n" +
	"\aTargets\x12\x1a.fatima.opm.v2.TargetQuery\x1a\x19.fatima.opm.v2.TargetList\x12>\n" +
	"\x06Create\x12\x1c.fatima.opm.v2.CreateRollout\x1a\x16.fatima.opm.v2.Rollout\x128\n" +
	"\x04List\x12\x14.fatima.opm.v2.Empty\x1a\x1a.fatima.opm.v2.RolloutList\x12:\n" +
	"\x03Get\x12\x1b.fatima.opm.v2.RolloutQuery\x1a\x16.fatima.opm.v2.Rollout\x12;\n" +
	"\x03Act\x12\x1c.fatima.opm.v2.RolloutAction\x1a\x16.fatima.opm.v2.Rollout\x12>\n" +
	"\x05Watch\x12\x1b.fatima.opm.v2.WatchRequest\x1a\x16.fatima.opm.v2.Rollout0\x012\xdb\x02\n" +
	"\x11PackageDeployment\x12@\n" +
	"\x06Cancel\x12\x1c.fatima.opm.v2.OperationSpec\x1a\x18.fatima.opm.v2.Operation\x12>\n" +
	"\x05Stage\x12\x19.fatima.opm.v2.StageChunk\x1a\x18.fatima.opm.v2.Operation(\x01\x12@\n" +
	"\x05Start\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x18.fatima.opm.v2.Operation\x12>\n" +
	"\x03Get\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x18.fatima.opm.v2.Operation\x12B\n" +
	"\x05Watch\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x18.fatima.opm.v2.Operation0\x01B)Z'github.com/fatima-go/fatima-opm/api;apib\x06proto3"

var (
	file_api_control_proto_rawDescOnce sync.Once
	file_api_control_proto_rawDescData []byte
)

func file_api_control_proto_rawDescGZIP() []byte {
	file_api_control_proto_rawDescOnce.Do(func() {
		file_api_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)))
	})
	return file_api_control_proto_rawDescData
}

var file_api_control_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_control_proto_goTypes = []any{
	(*Empty)(nil),                // 0: fatima.opm.v2.Empty
	(*Capabilities)(nil),         // 1: fatima.opm.v2.Capabilities
	(*LoginRequest)(nil),         // 2: fatima.opm.v2.LoginRequest
	(*Session)(nil),              // 3: fatima.opm.v2.Session
	(*ValidateRequest)(nil),      // 4: fatima.opm.v2.ValidateRequest
	(*Artifact)(nil),             // 5: fatima.opm.v2.Artifact
	(*UploadHeader)(nil),         // 6: fatima.opm.v2.UploadHeader
	(*UploadChunk)(nil),          // 7: fatima.opm.v2.UploadChunk
	(*ArtifactQuery)(nil),        // 8: fatima.opm.v2.ArtifactQuery
	(*ArtifactList)(nil),         // 9: fatima.opm.v2.ArtifactList
	(*Target)(nil),               // 10: fatima.opm.v2.Target
	(*TargetQuery)(nil),          // 11: fatima.opm.v2.TargetQuery
	(*TargetList)(nil),           // 12: fatima.opm.v2.TargetList
	(*CreateRollout)(nil),        // 13: fatima.opm.v2.CreateRollout
	(*RolloutQuery)(nil),         // 14: fatima.opm.v2.RolloutQuery
	(*RolloutList)(nil),          // 15: fatima.opm.v2.RolloutList
	(*RolloutAction)(nil),        // 16: fatima.opm.v2.RolloutAction
	(*WatchRequest)(nil),         // 17: fatima.opm.v2.WatchRequest
	(*Event)(nil),                // 18: fatima.opm.v2.Event
	(*Operation)(nil),            // 19: fatima.opm.v2.Operation
	(*TargetRun)(nil),            // 20: fatima.opm.v2.TargetRun
	(*Rollout)(nil),              // 21: fatima.opm.v2.Rollout
	(*ManagementCredential)(nil), // 22: fatima.opm.v2.ManagementCredential
	(*ManagementSession)(nil),    // 23: fatima.opm.v2.ManagementSession
	(*RolloutConflict)(nil),      // 24: fatima.opm.v2.RolloutConflict
	(*OperationSpec)(nil),        // 25: fatima.opm.v2.OperationSpec
	(*StageChunk)(nil),           // 26: fatima.opm.v2.StageChunk
	(*OperationQuery)(nil),       // 27: fatima.opm.v2.OperationQuery
}
var file_api_control_proto_depIdxs = []int32{
	6,  // 0: fatima.opm.v2.UploadChunk.header:type_name -> fatima.opm.v2.UploadHeader
	5,  // 1: fatima.opm.v2.ArtifactList.artifacts:type_name -> fatima.opm.v2.Artifact
	10, // 2: fatima.opm.v2.TargetList.targets:type_name -> fatima.opm.v2.Target
	22, // 3: fatima.opm.v2.CreateRollout.management:type_name -> fatima.opm.v2.ManagementCredential
	21, // 4: fatima.opm.v2.RolloutList.rollouts:type_name -> fatima.opm.v2.Rollout
	18, // 5: fatima.opm.v2.Operation.events:type_name -> fatima.opm.v2.Event
	10, // 6: fatima.opm.v2.TargetRun.target:type_name -> fatima.opm.v2.Target
	19, // 7: fatima.opm.v2.TargetRun.operation:type_name -> fatima.opm.v2.Operation
	19, // 8: fatima.opm.v2.TargetRun.previous_attempts:type_name -> fatima.opm.v2.Operation
	5,  // 9: fatima.opm.v2.Rollout.artifact:type_name -> fatima.opm.v2.Artifact
	20, // 10: fatima.opm.v2.Rollout.targets:type_name -> fatima.opm.v2.TargetRun
	25, // 11: fatima.opm.v2.StageChunk.spec:type_name -> fatima.opm.v2.OperationSpec
	0,  // 12: fatima.opm.v2.Discovery.GetCapabilities:input_type -> fatima.opm.v2.Empty
	2,  // 13: fatima.opm.v2.Identity.Login:input_type -> fatima.opm.v2.LoginRequest
	4,  // 14: fatima.opm.v2.Identity.Validate:input_type -> fatima.opm.v2.ValidateRequest
	7,  // 15: fatima.opm.v2.Artifacts.Upload:input_type -> fatima.opm.v2.UploadChunk
	8,  // 16: fatima.opm.v2.Artifacts.List:input_type -> fatima.opm.v2.ArtifactQuery
	8,  // 17: fatima.opm.v2.Artifacts.Get:input_type -> fatima.opm.v2.ArtifactQuery
	0,  // 18: fatima.opm.v2.DeploymentManagement.Open:input_type -> fatima.opm.v2.Empty
	22, // 19: fatima.opm.v2.DeploymentManagement.Heartbeat:input_type -> fatima.opm.v2.ManagementCredential
	22, // 20: fatima.opm.v2.DeploymentManagement.Detach:input_type -> fatima.opm.v2.ManagementCredential
	11, // 21: fatima.opm.v2.Deployments.Targets:input_type -> fatima.opm.v2.TargetQuery
	13, // 22: fatima.opm.v2.Deployments.Create:input_type -> fatima.opm.v2.CreateRollout
	0,  // 23: fatima.opm.v2.Deployments.List:input_type -> fatima.opm.v2.Empty
	14, // 24: fatima.opm.v2.Deployments.Get:input_type -> fatima.opm.v2.RolloutQuery
	16, // 25: fatima.opm.v2.Deployments.Act:input_type -> fatima.opm.v2.RolloutAction
	17, // 26: fatima.opm.v2.Deployments.Watch:input_type -> fatima.opm.v2.WatchRequest
	25, // 27: fatima.opm.v2.PackageDeployment.Cancel:input_type -> fatima.opm.v2.OperationSpec
	26, // 28: fatima.opm.v2.PackageDeployment.Stage:input_type -> fatima.opm.v2.StageChunk
	27, // 29: fatima.opm.v2.PackageDeployment.Start:input_type -> fatima.opm.v2.OperationQuery
	27, // 30: fatima.opm.v2.PackageDeployment.Get:input_type -> fatima.opm.v2.OperationQuery
	27, // 31: fatima.opm.v2.PackageDeployment.Watch:input_type -> fatima.opm.v2.OperationQuery
	1,  // 32: fatima.opm.v2.Discovery.GetCapabilities:output_type -> fatima.opm.v2.Capabilities
	3,  // 33: fatima.opm.v2.Identity.Login:output_type -> fatima.opm.v2.Session
	3,  // 34: fatima.opm.v2.Identity.Validate:output_type -> fatima.opm.v2.Session
	5,  // 35: fatima.opm.v2.Artifacts.Upload:output_type -> fatima.opm.v2.Artifact
	9,  // 36: fatima.opm.v2.Artifacts.List:output_type -> fatima.opm.v2.ArtifactList
	5,  // 37: fatima.opm.v2.Artifacts.Get:output_type -> fatima.opm.v2.Artifact
	23, // 38: fatima.opm.v2.DeploymentManagement.Open:output_type -> fatima.opm.v2.ManagementSession
	23, // 39: fatima.opm.v2.DeploymentManagement.Heartbeat:output_type -> fatima.opm.v2.ManagementSession
	23, // 40: fatima.opm.v2.DeploymentManagement.Detach:output_type -> fatima.opm.v2.ManagementSession
	12, // 41: fatima.opm.v2.Deployments.Targets:output_type -> fatima.opm.v2.TargetList
	21, // 42: fatima.opm.v2.Deployments.Create:output_type -> fatima.opm.v2.Rollout
	15, // 43: fatima.opm.v2.Deployments.List:output_type -> fatima.opm.v2.RolloutList
	21, // 44: fatima.opm.v2.Deployments.Get:output_type -> fatima.opm.v2.Rollout
	21, // 45: fatima.opm.v2.Deployments.Act:output_type -> fatima.opm.v2.Rollout
	21, // 46: fatima.opm.v2.Deployments.Watch:output_type -> fatima.opm.v2.Rollout
	19, // 47: fatima.opm.v2.PackageDeployment.Cancel:output_type -> fatima.opm.v2.Operation
	19, // 48: fatima.opm.v2.PackageDeployment.Stage:output_type -> fatima.opm.v2.Operation
	19, // 49: fatima.opm.v2.PackageDeployment.Start:output_type -> fatima.opm.v2.Operation
	19, // 50: fatima.opm.v2.PackageDeployment.Get:output_type -> fatima.opm.v2.Operation
	19, // 51: fatima.opm.v2.PackageDeployment.Watch:output_type -> fatima.opm.v2.Operation
	32, // [32:52] is the sub-list for method output_type
	12, // [12:32] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_control_proto_init() }
func file_api_control_proto_init() {
	if File_api_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_api_control_proto_goTypes,
		DependencyIndexes: file_api_control_proto_depIdxs,
		MessageInfos:      file_api_control_proto_msgTypes,
	}.Build()
	File_api_control_proto = out.File
	file_api_control_proto_goTypes = nil
	file_api_control_proto_depIdxs = nil
}
