// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: api/operations.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Routing_Resolve_FullMethodName = "/fatima.opm.v2.Routing/Resolve"
)

// RoutingClient is the client API for Routing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingClient interface {
	Resolve(ctx context.Context, in *PackageQuery, opts ...grpc.CallOption) (*Target, error)
}

type routingClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingClient(cc grpc.ClientConnInterface) RoutingClient {
	return &routingClient{cc}
}

func (c *routingClient) Resolve(ctx context.Context, in *PackageQuery, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, Routing_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServer is the server API for Routing service.
// All implementations must embed UnimplementedRoutingServer
// for forward compatibility.
type RoutingServer interface {
	Resolve(context.Context, *PackageQuery) (*Target, error)
	mustEmbedUnimplementedRoutingServer()
}

// UnimplementedRoutingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServer struct{}

func (UnimplementedRoutingServer) Resolve(context.Context, *PackageQuery) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedRoutingServer) mustEmbedUnimplementedRoutingServer() {}
func (UnimplementedRoutingServer) testEmbeddedByValue()                 {}

// UnsafeRoutingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServer will
// result in compilation errors.
type UnsafeRoutingServer interface {
	mustEmbedUnimplementedRoutingServer()
}

func RegisterRoutingServer(s grpc.ServiceRegistrar, srv RoutingServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Routing_ServiceDesc, srv)
}

func _Routing_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Routing_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServer).Resolve(ctx, req.(*PackageQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Routing_ServiceDesc is the grpc.ServiceDesc for Routing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Routing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.Routing",
	HandlerType: (*RoutingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Routing_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/operations.proto",
}

const (
	PackageInventory_List_FullMethodName  = "/fatima.opm.v2.PackageInventory/List"
	PackageInventory_Watch_FullMethodName = "/fatima.opm.v2.PackageInventory/Watch"
)

// PackageInventoryClient is the client API for PackageInventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackageInventoryClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageCatalog, error)
	Watch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageCatalog], error)
}

type packageInventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageInventoryClient(cc grpc.ClientConnInterface) PackageInventoryClient {
	return &packageInventoryClient{cc}
}

func (c *packageInventoryClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageCatalog)
	err := c.cc.Invoke(ctx, PackageInventory_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageInventoryClient) Watch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageCatalog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageInventory_ServiceDesc.Streams[0], PackageInventory_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PackageCatalog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageInventory_WatchClient = grpc.ServerStreamingClient[PackageCatalog]

// PackageInventoryServer is the server API for PackageInventory service.
// All implementations must embed UnimplementedPackageInventoryServer
// for forward compatibility.
type PackageInventoryServer interface {
	List(context.Context, *Empty) (*PackageCatalog, error)
	Watch(*Empty, grpc.ServerStreamingServer[PackageCatalog]) error
	mustEmbedUnimplementedPackageInventoryServer()
}

// UnimplementedPackageInventoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackageInventoryServer struct{}

func (UnimplementedPackageInventoryServer) List(context.Context, *Empty) (*PackageCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPackageInventoryServer) Watch(*Empty, grpc.ServerStreamingServer[PackageCatalog]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedPackageInventoryServer) mustEmbedUnimplementedPackageInventoryServer() {}
func (UnimplementedPackageInventoryServer) testEmbeddedByValue()                          {}

// UnsafePackageInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageInventoryServer will
// result in compilation errors.
type UnsafePackageInventoryServer interface {
	mustEmbedUnimplementedPackageInventoryServer()
}

func RegisterPackageInventoryServer(s grpc.ServiceRegistrar, srv PackageInventoryServer) {
	// If the following call pancis, it indicates UnimplementedPackageInventoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackageInventory_ServiceDesc, srv)
}

func _PackageInventory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageInventoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageInventory_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageInventoryServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageInventory_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageInventoryServer).Watch(m, &grpc.GenericServerStream[Empty, PackageCatalog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageInventory_WatchServer = grpc.ServerStreamingServer[PackageCatalog]

// PackageInventory_ServiceDesc is the grpc.ServiceDesc for PackageInventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackageInventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.PackageInventory",
	HandlerType: (*PackageInventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PackageInventory_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _PackageInventory_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/operations.proto",
}

const (
	CronControl_List_FullMethodName  = "/fatima.opm.v2.CronControl/List"
	CronControl_Rerun_FullMethodName = "/fatima.opm.v2.CronControl/Rerun"
	CronControl_Get_FullMethodName   = "/fatima.opm.v2.CronControl/Get"
	CronControl_Watch_FullMethodName = "/fatima.opm.v2.CronControl/Watch"
)

// CronControlClient is the client API for CronControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronControlClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CronCatalog, error)
	Rerun(ctx context.Context, in *CronRequest, opts ...grpc.CallOption) (*ControlOperation, error)
	Get(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*ControlOperation, error)
	Watch(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlOperation], error)
}

type cronControlClient struct {
	cc grpc.ClientConnInterface
}

func NewCronControlClient(cc grpc.ClientConnInterface) CronControlClient {
	return &cronControlClient{cc}
}

func (c *cronControlClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CronCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronCatalog)
	err := c.cc.Invoke(ctx, CronControl_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronControlClient) Rerun(ctx context.Context, in *CronRequest, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, CronControl_Rerun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronControlClient) Get(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, CronControl_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronControlClient) Watch(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlOperation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CronControl_ServiceDesc.Streams[0], CronControl_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OperationQuery, ControlOperation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CronControl_WatchClient = grpc.ServerStreamingClient[ControlOperation]

// CronControlServer is the server API for CronControl service.
// All implementations must embed UnimplementedCronControlServer
// for forward compatibility.
type CronControlServer interface {
	List(context.Context, *Empty) (*CronCatalog, error)
	Rerun(context.Context, *CronRequest) (*ControlOperation, error)
	Get(context.Context, *OperationQuery) (*ControlOperation, error)
	Watch(*OperationQuery, grpc.ServerStreamingServer[ControlOperation]) error
	mustEmbedUnimplementedCronControlServer()
}

// UnimplementedCronControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCronControlServer struct{}

func (UnimplementedCronControlServer) List(context.Context, *Empty) (*CronCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCronControlServer) Rerun(context.Context, *CronRequest) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rerun not implemented")
}
func (UnimplementedCronControlServer) Get(context.Context, *OperationQuery) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCronControlServer) Watch(*OperationQuery, grpc.ServerStreamingServer[ControlOperation]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedCronControlServer) mustEmbedUnimplementedCronControlServer() {}
func (UnimplementedCronControlServer) testEmbeddedByValue()                     {}

// UnsafeCronControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronControlServer will
// result in compilation errors.
type UnsafeCronControlServer interface {
	mustEmbedUnimplementedCronControlServer()
}

func RegisterCronControlServer(s grpc.ServiceRegistrar, srv CronControlServer) {
	// If the following call pancis, it indicates UnimplementedCronControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CronControl_ServiceDesc, srv)
}

func _CronControl_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronControlServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronControl_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronControlServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronControl_Rerun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronControlServer).Rerun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronControl_Rerun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronControlServer).Rerun(ctx, req.(*CronRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronControl_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronControlServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronControl_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronControlServer).Get(ctx, req.(*OperationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronControl_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OperationQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CronControlServer).Watch(m, &grpc.GenericServerStream[OperationQuery, ControlOperation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CronControl_WatchServer = grpc.ServerStreamingServer[ControlOperation]

// CronControl_ServiceDesc is the grpc.ServiceDesc for CronControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.CronControl",
	HandlerType: (*CronControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CronControl_List_Handler,
		},
		{
			MethodName: "Rerun",
			Handler:    _CronControl_Rerun_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CronControl_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _CronControl_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/operations.proto",
}

const (
	ProcessControl_Catalog_FullMethodName      = "/fatima.opm.v2.ProcessControl/Catalog"
	ProcessControl_WatchCatalog_FullMethodName = "/fatima.opm.v2.ProcessControl/WatchCatalog"
	ProcessControl_Stop_FullMethodName         = "/fatima.opm.v2.ProcessControl/Stop"
	ProcessControl_Start_FullMethodName        = "/fatima.opm.v2.ProcessControl/Start"
	ProcessControl_Get_FullMethodName          = "/fatima.opm.v2.ProcessControl/Get"
	ProcessControl_Watch_FullMethodName        = "/fatima.opm.v2.ProcessControl/Watch"
)

// ProcessControlClient is the client API for ProcessControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessControlClient interface {
	Catalog(ctx context.Context, in *ProcessQuery, opts ...grpc.CallOption) (*ProcessCatalog, error)
	WatchCatalog(ctx context.Context, in *ProcessQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessCatalog], error)
	Stop(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ControlOperation, error)
	Start(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ControlOperation, error)
	Get(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*ControlOperation, error)
	Watch(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlOperation], error)
}

type processControlClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessControlClient(cc grpc.ClientConnInterface) ProcessControlClient {
	return &processControlClient{cc}
}

func (c *processControlClient) Catalog(ctx context.Context, in *ProcessQuery, opts ...grpc.CallOption) (*ProcessCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessCatalog)
	err := c.cc.Invoke(ctx, ProcessControl_Catalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) WatchCatalog(ctx context.Context, in *ProcessQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessCatalog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessControl_ServiceDesc.Streams[0], ProcessControl_WatchCatalog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessQuery, ProcessCatalog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessControl_WatchCatalogClient = grpc.ServerStreamingClient[ProcessCatalog]

func (c *processControlClient) Stop(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, ProcessControl_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) Start(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, ProcessControl_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) Get(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, ProcessControl_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) Watch(ctx context.Context, in *OperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlOperation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessControl_ServiceDesc.Streams[1], ProcessControl_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OperationQuery, ControlOperation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessControl_WatchClient = grpc.ServerStreamingClient[ControlOperation]

// ProcessControlServer is the server API for ProcessControl service.
// All implementations must embed UnimplementedProcessControlServer
// for forward compatibility.
type ProcessControlServer interface {
	Catalog(context.Context, *ProcessQuery) (*ProcessCatalog, error)
	WatchCatalog(*ProcessQuery, grpc.ServerStreamingServer[ProcessCatalog]) error
	Stop(context.Context, *ProcessRequest) (*ControlOperation, error)
	Start(context.Context, *ProcessRequest) (*ControlOperation, error)
	Get(context.Context, *OperationQuery) (*ControlOperation, error)
	Watch(*OperationQuery, grpc.ServerStreamingServer[ControlOperation]) error
	mustEmbedUnimplementedProcessControlServer()
}

// UnimplementedProcessControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessControlServer struct{}

func (UnimplementedProcessControlServer) Catalog(context.Context, *ProcessQuery) (*ProcessCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Catalog not implemented")
}
func (UnimplementedProcessControlServer) WatchCatalog(*ProcessQuery, grpc.ServerStreamingServer[ProcessCatalog]) error {
	return status.Errorf(codes.Unimplemented, "method WatchCatalog not implemented")
}
func (UnimplementedProcessControlServer) Stop(context.Context, *ProcessRequest) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedProcessControlServer) Start(context.Context, *ProcessRequest) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedProcessControlServer) Get(context.Context, *OperationQuery) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProcessControlServer) Watch(*OperationQuery, grpc.ServerStreamingServer[ControlOperation]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedProcessControlServer) mustEmbedUnimplementedProcessControlServer() {}
func (UnimplementedProcessControlServer) testEmbeddedByValue()                        {}

// UnsafeProcessControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessControlServer will
// result in compilation errors.
type UnsafeProcessControlServer interface {
	mustEmbedUnimplementedProcessControlServer()
}

func RegisterProcessControlServer(s grpc.ServiceRegistrar, srv ProcessControlServer) {
	// If the following call pancis, it indicates UnimplementedProcessControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessControl_ServiceDesc, srv)
}

func _ProcessControl_Catalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).Catalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_Catalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).Catalog(ctx, req.(*ProcessQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_WatchCatalog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessControlServer).WatchCatalog(m, &grpc.GenericServerStream[ProcessQuery, ProcessCatalog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessControl_WatchCatalogServer = grpc.ServerStreamingServer[ProcessCatalog]

func _ProcessControl_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).Stop(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).Start(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).Get(ctx, req.(*OperationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OperationQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessControlServer).Watch(m, &grpc.GenericServerStream[OperationQuery, ControlOperation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessControl_WatchServer = grpc.ServerStreamingServer[ControlOperation]

// ProcessControl_ServiceDesc is the grpc.ServiceDesc for ProcessControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.ProcessControl",
	HandlerType: (*ProcessControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Catalog",
			Handler:    _ProcessControl_Catalog_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ProcessControl_Stop_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _ProcessControl_Start_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProcessControl_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCatalog",
			Handler:       _ProcessControl_WatchCatalog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _ProcessControl_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/operations.proto",
}

const (
	ProcessRegistry_Catalog_FullMethodName = "/fatima.opm.v2.ProcessRegistry/Catalog"
	ProcessRegistry_Preview_FullMethodName = "/fatima.opm.v2.ProcessRegistry/Preview"
	ProcessRegistry_Apply_FullMethodName   = "/fatima.opm.v2.ProcessRegistry/Apply"
	ProcessRegistry_Get_FullMethodName     = "/fatima.opm.v2.ProcessRegistry/Get"
	ProcessRegistry_Watch_FullMethodName   = "/fatima.opm.v2.ProcessRegistry/Watch"
)

// ProcessRegistryClient is the client API for ProcessRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Jupiter forwards this service; Juno owns validation, effects and durable results.
type ProcessRegistryClient interface {
	Catalog(ctx context.Context, in *RegistryQuery, opts ...grpc.CallOption) (*RegistryCatalog, error)
	Preview(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*RegistryPlan, error)
	Apply(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*ControlOperation, error)
	Get(ctx context.Context, in *RegistryOperationQuery, opts ...grpc.CallOption) (*ControlOperation, error)
	Watch(ctx context.Context, in *RegistryOperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlOperation], error)
}

type processRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessRegistryClient(cc grpc.ClientConnInterface) ProcessRegistryClient {
	return &processRegistryClient{cc}
}

func (c *processRegistryClient) Catalog(ctx context.Context, in *RegistryQuery, opts ...grpc.CallOption) (*RegistryCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryCatalog)
	err := c.cc.Invoke(ctx, ProcessRegistry_Catalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processRegistryClient) Preview(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*RegistryPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryPlan)
	err := c.cc.Invoke(ctx, ProcessRegistry_Preview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processRegistryClient) Apply(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, ProcessRegistry_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processRegistryClient) Get(ctx context.Context, in *RegistryOperationQuery, opts ...grpc.CallOption) (*ControlOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlOperation)
	err := c.cc.Invoke(ctx, ProcessRegistry_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processRegistryClient) Watch(ctx context.Context, in *RegistryOperationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlOperation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessRegistry_ServiceDesc.Streams[0], ProcessRegistry_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegistryOperationQuery, ControlOperation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessRegistry_WatchClient = grpc.ServerStreamingClient[ControlOperation]

// ProcessRegistryServer is the server API for ProcessRegistry service.
// All implementations must embed UnimplementedProcessRegistryServer
// for forward compatibility.
//
// Jupiter forwards this service; Juno owns validation, effects and durable results.
type ProcessRegistryServer interface {
	Catalog(context.Context, *RegistryQuery) (*RegistryCatalog, error)
	Preview(context.Context, *RegistryRequest) (*RegistryPlan, error)
	Apply(context.Context, *RegistryRequest) (*ControlOperation, error)
	Get(context.Context, *RegistryOperationQuery) (*ControlOperation, error)
	Watch(*RegistryOperationQuery, grpc.ServerStreamingServer[ControlOperation]) error
	mustEmbedUnimplementedProcessRegistryServer()
}

// UnimplementedProcessRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessRegistryServer struct{}

func (UnimplementedProcessRegistryServer) Catalog(context.Context, *RegistryQuery) (*RegistryCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Catalog not implemented")
}
func (UnimplementedProcessRegistryServer) Preview(context.Context, *RegistryRequest) (*RegistryPlan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Preview not implemented")
}
func (UnimplementedProcessRegistryServer) Apply(context.Context, *RegistryRequest) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedProcessRegistryServer) Get(context.Context, *RegistryOperationQuery) (*ControlOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProcessRegistryServer) Watch(*RegistryOperationQuery, grpc.ServerStreamingServer[ControlOperation]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedProcessRegistryServer) mustEmbedUnimplementedProcessRegistryServer() {}
func (UnimplementedProcessRegistryServer) testEmbeddedByValue()                         {}

// UnsafeProcessRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessRegistryServer will
// result in compilation errors.
type UnsafeProcessRegistryServer interface {
	mustEmbedUnimplementedProcessRegistryServer()
}

func RegisterProcessRegistryServer(s grpc.ServiceRegistrar, srv ProcessRegistryServer) {
	// If the following call pancis, it indicates UnimplementedProcessRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessRegistry_ServiceDesc, srv)
}

func _ProcessRegistry_Catalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessRegistryServer).Catalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessRegistry_Catalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessRegistryServer).Catalog(ctx, req.(*RegistryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessRegistry_Preview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessRegistryServer).Preview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessRegistry_Preview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessRegistryServer).Preview(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessRegistry_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessRegistryServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessRegistry_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessRegistryServer).Apply(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessRegistry_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryOperationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessRegistryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessRegistry_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessRegistryServer).Get(ctx, req.(*RegistryOperationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessRegistry_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegistryOperationQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessRegistryServer).Watch(m, &grpc.GenericServerStream[RegistryOperationQuery, ControlOperation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessRegistry_WatchServer = grpc.ServerStreamingServer[ControlOperation]

// ProcessRegistry_ServiceDesc is the grpc.ServiceDesc for ProcessRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.ProcessRegistry",
	HandlerType: (*ProcessRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Catalog",
			Handler:    _ProcessRegistry_Catalog_Handler,
		},
		{
			MethodName: "Preview",
			Handler:    _ProcessRegistry_Preview_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _ProcessRegistry_Apply_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProcessRegistry_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ProcessRegistry_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/operations.proto",
}

const (
	LogLevelControl_List_FullMethodName = "/fatima.opm.v2.LogLevelControl/List"
	LogLevelControl_Set_FullMethodName  = "/fatima.opm.v2.LogLevelControl/Set"
)

// LogLevelControlClient is the client API for LogLevelControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Juno updates the package loglevels file; each process applies it on its next one-second check.
type LogLevelControlClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelCatalog, error)
	Set(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelEntry, error)
}

type logLevelControlClient struct {
	cc grpc.ClientConnInterface
}

func NewLogLevelControlClient(cc grpc.ClientConnInterface) LogLevelControlClient {
	return &logLevelControlClient{cc}
}

func (c *logLevelControlClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelCatalog)
	err := c.cc.Invoke(ctx, LogLevelControl_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logLevelControlClient) Set(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelEntry)
	err := c.cc.Invoke(ctx, LogLevelControl_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogLevelControlServer is the server API for LogLevelControl service.
// All implementations must embed UnimplementedLogLevelControlServer
// for forward compatibility.
//
// Juno updates the package loglevels file; each process applies it on its next one-second check.
type LogLevelControlServer interface {
	List(context.Context, *Empty) (*LogLevelCatalog, error)
	Set(context.Context, *LogLevelRequest) (*LogLevelEntry, error)
	mustEmbedUnimplementedLogLevelControlServer()
}

// UnimplementedLogLevelControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogLevelControlServer struct{}

func (UnimplementedLogLevelControlServer) List(context.Context, *Empty) (*LogLevelCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLogLevelControlServer) Set(context.Context, *LogLevelRequest) (*LogLevelEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedLogLevelControlServer) mustEmbedUnimplementedLogLevelControlServer() {}
func (UnimplementedLogLevelControlServer) testEmbeddedByValue()                         {}

// UnsafeLogLevelControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogLevelControlServer will
// result in compilation errors.
type UnsafeLogLevelControlServer interface {
	mustEmbedUnimplementedLogLevelControlServer()
}

func RegisterLogLevelControlServer(s grpc.ServiceRegistrar, srv LogLevelControlServer) {
	// If the following call pancis, it indicates UnimplementedLogLevelControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogLevelControl_ServiceDesc, srv)
}

func _LogLevelControl_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogLevelControlServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogLevelControl_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogLevelControlServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogLevelControl_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogLevelControlServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogLevelControl_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogLevelControlServer).Set(ctx, req.(*LogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogLevelControl_ServiceDesc is the grpc.ServiceDesc for LogLevelControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogLevelControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.LogLevelControl",
	HandlerType: (*LogLevelControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LogLevelControl_List_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _LogLevelControl_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/operations.proto",
}

const (
	DeploymentHistory_List_FullMethodName = "/fatima.opm.v2.DeploymentHistory/List"
)

// DeploymentHistoryClient is the client API for DeploymentHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Juno reads the history it keeps per process at each deployment, newest first.
// An empty process lists every registered process.
type DeploymentHistoryClient interface {
	List(ctx context.Context, in *HistoryQuery, opts ...grpc.CallOption) (*HistoryList, error)
}

type deploymentHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentHistoryClient(cc grpc.ClientConnInterface) DeploymentHistoryClient {
	return &deploymentHistoryClient{cc}
}

func (c *deploymentHistoryClient) List(ctx context.Context, in *HistoryQuery, opts ...grpc.CallOption) (*HistoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryList)
	err := c.cc.Invoke(ctx, DeploymentHistory_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentHistoryServer is the server API for DeploymentHistory service.
// All implementations must embed UnimplementedDeploymentHistoryServer
// for forward compatibility.
//
// Juno reads the history it keeps per process at each deployment, newest first.
// An empty process lists every registered process.
type DeploymentHistoryServer interface {
	List(context.Context, *HistoryQuery) (*HistoryList, error)
	mustEmbedUnimplementedDeploymentHistoryServer()
}

// UnimplementedDeploymentHistoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentHistoryServer struct{}

func (UnimplementedDeploymentHistoryServer) List(context.Context, *HistoryQuery) (*HistoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDeploymentHistoryServer) mustEmbedUnimplementedDeploymentHistoryServer() {}
func (UnimplementedDeploymentHistoryServer) testEmbeddedByValue()                           {}

// UnsafeDeploymentHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentHistoryServer will
// result in compilation errors.
type UnsafeDeploymentHistoryServer interface {
	mustEmbedUnimplementedDeploymentHistoryServer()
}

func RegisterDeploymentHistoryServer(s grpc.ServiceRegistrar, srv DeploymentHistoryServer) {
	// If the following call pancis, it indicates UnimplementedDeploymentHistoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentHistory_ServiceDesc, srv)
}

func _DeploymentHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentHistory_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentHistoryServer).List(ctx, req.(*HistoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentHistory_ServiceDesc is the grpc.ServiceDesc for DeploymentHistory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentHistory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fatima.opm.v2.DeploymentHistory",
	HandlerType: (*DeploymentHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DeploymentHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/operations.proto",
}
