// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.36.0
// source: api/operations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageQuery) Reset() {
	*x = PackageQuery{}
	mi := &file_api_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageQuery) ProtoMessage() {}

func (x *PackageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageQuery.ProtoReflect.Descriptor instead.
func (*PackageQuery) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{0}
}

func (x *PackageQuery) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

type PackageEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Transport     string                 `protobuf:"bytes,6,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageEntry) Reset() {
	*x = PackageEntry{}
	mi := &file_api_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageEntry) ProtoMessage() {}

func (x *PackageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageEntry.ProtoReflect.Descriptor instead.
func (*PackageEntry) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{1}
}

func (x *PackageEntry) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PackageEntry) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *PackageEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PackageEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PackageEntry) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *PackageEntry) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type PackageCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*PackageEntry        `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	ObservedAt    int64                  `protobuf:"varint,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageCatalog) Reset() {
	*x = PackageCatalog{}
	mi := &file_api_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageCatalog) ProtoMessage() {}

func (x *PackageCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageCatalog.ProtoReflect.Descriptor instead.
func (*PackageCatalog) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{2}
}

func (x *PackageCatalog) GetPackages() []*PackageEntry {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackageCatalog) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

type CronEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Spec          string                 `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Sample        string                 `protobuf:"bytes,5,opt,name=sample,proto3" json:"sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronEntry) Reset() {
	*x = CronEntry{}
	mi := &file_api_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronEntry) ProtoMessage() {}

func (x *CronEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronEntry.ProtoReflect.Descriptor instead.
func (*CronEntry) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{3}
}

func (x *CronEntry) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *CronEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CronEntry) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *CronEntry) GetSample() string {
	if x != nil {
		return x.Sample
	}
	return ""
}

type CronHour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Jobs          []*CronEntry           `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronHour) Reset() {
	*x = CronHour{}
	mi := &file_api_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronHour) ProtoMessage() {}

func (x *CronHour) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronHour.ProtoReflect.Descriptor instead.
func (*CronHour) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{4}
}

func (x *CronHour) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *CronHour) GetJobs() []*CronEntry {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CronCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Jobs          []*CronEntry           `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Hours         []*CronHour            `protobuf:"bytes,3,rep,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronCatalog) Reset() {
	*x = CronCatalog{}
	mi := &file_api_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronCatalog) ProtoMessage() {}

func (x *CronCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronCatalog.ProtoReflect.Descriptor instead.
func (*CronCatalog) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{5}
}

func (x *CronCatalog) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *CronCatalog) GetJobs() []*CronEntry {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *CronCatalog) GetHours() []*CronHour {
	if x != nil {
		return x.Hours
	}
	return nil
}

type CronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Process       string                 `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	Job           string                 `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	Arguments     string                 `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRequest) Reset() {
	*x = CronRequest{}
	mi := &file_api_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRequest) ProtoMessage() {}

func (x *CronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRequest.ProtoReflect.Descriptor instead.
func (*CronRequest) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{6}
}

func (x *CronRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CronRequest) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *CronRequest) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *CronRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// REQUESTED means delivery only. It must never be presented as batch success.
type ControlOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	PackageId     string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Events        []*Event               `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlOperation) Reset() {
	*x = ControlOperation{}
	mi := &file_api_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlOperation) ProtoMessage() {}

func (x *ControlOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlOperation.ProtoReflect.Descriptor instead.
func (*ControlOperation) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{7}
}

func (x *ControlOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlOperation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ControlOperation) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *ControlOperation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ControlOperation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlOperation) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ControlOperation) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ControlOperation) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type ProcessQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessQuery) Reset() {
	*x = ProcessQuery{}
	mi := &file_api_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessQuery) ProtoMessage() {}

func (x *ProcessQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessQuery.ProtoReflect.Descriptor instead.
func (*ProcessQuery) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessQuery) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type ProcessEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid           string                 `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Cpu           string                 `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Fd            string                 `protobuf:"bytes,7,opt,name=fd,proto3" json:"fd,omitempty"`
	Threads       string                 `protobuf:"bytes,8,opt,name=threads,proto3" json:"threads,omitempty"`
	StartedAt     string                 `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Ic            string                 `protobuf:"bytes,10,opt,name=ic,proto3" json:"ic,omitempty"`
	Index         int32                  `protobuf:"varint,11,opt,name=index,proto3" json:"index,omitempty"`
	Opm           bool                   `protobuf:"varint,12,opt,name=opm,proto3" json:"opm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEntry) Reset() {
	*x = ProcessEntry{}
	mi := &file_api_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEntry) ProtoMessage() {}

func (x *ProcessEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEntry.ProtoReflect.Descriptor instead.
func (*ProcessEntry) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessEntry) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ProcessEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessEntry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ProcessEntry) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ProcessEntry) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ProcessEntry) GetFd() string {
	if x != nil {
		return x.Fd
	}
	return ""
}

func (x *ProcessEntry) GetThreads() string {
	if x != nil {
		return x.Threads
	}
	return ""
}

func (x *ProcessEntry) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ProcessEntry) GetIc() string {
	if x != nil {
		return x.Ic
	}
	return ""
}

func (x *ProcessEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProcessEntry) GetOpm() bool {
	if x != nil {
		return x.Opm
	}
	return false
}

type ProcessCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	HaStatus      int32                  `protobuf:"varint,4,opt,name=ha_status,json=haStatus,proto3" json:"ha_status,omitempty"`
	PsStatus      int32                  `protobuf:"varint,5,opt,name=ps_status,json=psStatus,proto3" json:"ps_status,omitempty"`
	Processes     []*ProcessEntry        `protobuf:"bytes,6,rep,name=processes,proto3" json:"processes,omitempty"`
	ObservedAt    int64                  `protobuf:"varint,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCatalog) Reset() {
	*x = ProcessCatalog{}
	mi := &file_api_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCatalog) ProtoMessage() {}

func (x *ProcessCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCatalog.ProtoReflect.Descriptor instead.
func (*ProcessCatalog) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessCatalog) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *ProcessCatalog) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ProcessCatalog) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ProcessCatalog) GetHaStatus() int32 {
	if x != nil {
		return x.HaStatus
	}
	return 0
}

func (x *ProcessCatalog) GetPsStatus() int32 {
	if x != nil {
		return x.PsStatus
	}
	return 0
}

func (x *ProcessCatalog) GetProcesses() []*ProcessEntry {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProcessCatalog) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Processes     []string               `protobuf:"bytes,2,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_api_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessRequest) GetProcesses() []string {
	if x != nil {
		return x.Processes
	}
	return nil
}

type RegistryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryQuery) Reset() {
	*x = RegistryQuery{}
	mi := &file_api_operations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryQuery) ProtoMessage() {}

func (x *RegistryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryQuery.ProtoReflect.Descriptor instead.
func (*RegistryQuery) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{12}
}

func (x *RegistryQuery) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *RegistryQuery) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type ProcessGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessGroup) Reset() {
	*x = ProcessGroup{}
	mi := &file_api_operations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGroup) ProtoMessage() {}

func (x *ProcessGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessGroup.ProtoReflect.Descriptor instead.
func (*ProcessGroup) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessGroup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegistryCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       *ProcessCatalog        `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Groups        []*ProcessGroup        `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCatalog) Reset() {
	*x = RegistryCatalog{}
	mi := &file_api_operations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCatalog) ProtoMessage() {}

func (x *RegistryCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCatalog.ProtoReflect.Descriptor instead.
func (*RegistryCatalog) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{14}
}

func (x *RegistryCatalog) GetCatalog() *ProcessCatalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *RegistryCatalog) GetGroups() []*ProcessGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *RegistryCatalog) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type RegistryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PackageId        string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action           string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Process          string                 `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	Group            string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	ExpectedRevision string                 `protobuf:"bytes,6,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistryRequest) Reset() {
	*x = RegistryRequest{}
	mi := &file_api_operations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRequest) ProtoMessage() {}

func (x *RegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRequest.ProtoReflect.Descriptor instead.
func (*RegistryRequest) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{15}
}

func (x *RegistryRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *RegistryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RegistryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RegistryRequest) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *RegistryRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RegistryRequest) GetExpectedRevision() string {
	if x != nil {
		return x.ExpectedRevision
	}
	return ""
}

type RegistryPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *RegistryRequest       `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Effects       []string               `protobuf:"bytes,2,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryPlan) Reset() {
	*x = RegistryPlan{}
	mi := &file_api_operations_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryPlan) ProtoMessage() {}

func (x *RegistryPlan) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryPlan.ProtoReflect.Descriptor instead.
func (*RegistryPlan) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{16}
}

func (x *RegistryPlan) GetRequest() *RegistryRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RegistryPlan) GetEffects() []string {
	if x != nil {
		return x.Effects
	}
	return nil
}

type RegistryOperationQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryOperationQuery) Reset() {
	*x = RegistryOperationQuery{}
	mi := &file_api_operations_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryOperationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryOperationQuery) ProtoMessage() {}

func (x *RegistryOperationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryOperationQuery.ProtoReflect.Descriptor instead.
func (*RegistryOperationQuery) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{17}
}

func (x *RegistryOperationQuery) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *RegistryOperationQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// level is one of error, warn, info, debug or trace; empty when unset.
type LogLevelEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Opm           bool                   `protobuf:"varint,4,opt,name=opm,proto3" json:"opm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelEntry) Reset() {
	*x = LogLevelEntry{}
	mi := &file_api_operations_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelEntry) ProtoMessage() {}

func (x *LogLevelEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelEntry.ProtoReflect.Descriptor instead.
func (*LogLevelEntry) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{18}
}

func (x *LogLevelEntry) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *LogLevelEntry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *LogLevelEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLevelEntry) GetOpm() bool {
	if x != nil {
		return x.Opm
	}
	return false
}

type LogLevelCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Entries       []*LogLevelEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelCatalog) Reset() {
	*x = LogLevelCatalog{}
	mi := &file_api_operations_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelCatalog) ProtoMessage() {}

func (x *LogLevelCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelCatalog.ProtoReflect.Descriptor instead.
func (*LogLevelCatalog) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{19}
}

func (x *LogLevelCatalog) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *LogLevelCatalog) GetEntries() []*LogLevelEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelRequest) Reset() {
	*x = LogLevelRequest{}
	mi := &file_api_operations_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelRequest) ProtoMessage() {}

func (x *LogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelRequest.ProtoReflect.Descriptor instead.
func (*LogLevelRequest) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{20}
}

func (x *LogLevelRequest) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *LogLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

// deployed_at is Unix time in milliseconds; build fields come from the artifact's deployment.json.
type DeploymentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	DeployedAt    int64                  `protobuf:"varint,3,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	BuildUser     string                 `protobuf:"bytes,4,opt,name=build_user,json=buildUser,proto3" json:"build_user,omitempty"`
	BuildTime     string                 `protobuf:"bytes,5,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	GitBranch     string                 `protobuf:"bytes,6,opt,name=git_branch,json=gitBranch,proto3" json:"git_branch,omitempty"`
	GitCommit     string                 `protobuf:"bytes,7,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	GitMessage    string                 `protobuf:"bytes,8,opt,name=git_message,json=gitMessage,proto3" json:"git_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentRecord) Reset() {
	*x = DeploymentRecord{}
	mi := &file_api_operations_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentRecord) ProtoMessage() {}

func (x *DeploymentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentRecord.ProtoReflect.Descriptor instead.
func (*DeploymentRecord) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{21}
}

func (x *DeploymentRecord) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *DeploymentRecord) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DeploymentRecord) GetDeployedAt() int64 {
	if x != nil {
		return x.DeployedAt
	}
	return 0
}

func (x *DeploymentRecord) GetBuildUser() string {
	if x != nil {
		return x.BuildUser
	}
	return ""
}

func (x *DeploymentRecord) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *DeploymentRecord) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *DeploymentRecord) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *DeploymentRecord) GetGitMessage() string {
	if x != nil {
		return x.GitMessage
	}
	return ""
}

type HistoryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryQuery) Reset() {
	*x = HistoryQuery{}
	mi := &file_api_operations_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryQuery) ProtoMessage() {}

func (x *HistoryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryQuery.ProtoReflect.Descriptor instead.
func (*HistoryQuery) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{22}
}

func (x *HistoryQuery) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

type HistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Records       []*DeploymentRecord    `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryList) Reset() {
	*x = HistoryList{}
	mi := &file_api_operations_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryList) ProtoMessage() {}

func (x *HistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_api_operations_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryList.ProtoReflect.Descriptor instead.
func (*HistoryList) Descriptor() ([]byte, []int) {
	return file_api_operations_proto_rawDescGZIP(), []int{23}
}

func (x *HistoryList) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *HistoryList) GetRecords() []*DeploymentRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_api_operations_proto protoreflect.FileDescriptor

const file_api_operations_proto_rawDesc = "" +
	"\n" +
	"\x14api/operations.proto\x12\rfatima.opm.v2\x1a\x11api/control.proto\"-\n" +
	"\fPackageQuery\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\"\xcd\x01\n" +
	"\fPackageEntry\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.fatima.opm.v2.TargetR\x06target\x12#\n" +
	"\rregistered_at\x18\x02 \x01(\x03R\fregisteredAt\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\x03R\tcheckedAt\x12\x1c\n" +
	"\ttransport\x18\x06 \x01(\tR\ttransport\"j\n" +
	"\x0ePackageCatalog\x127\n" +
	"\bpackages\x18\x01 \x03(\v2\x1b.fatima.opm.v2.PackageEntryR\bpackages\x12\x1f\n" +
	"\vobserved_at\x18\x02 \x01(\x03R\n" +
	"observedAt\"\x87\x01\n" +
	"\tCronEntry\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04spec\x18\x04 \x01(\tR\x04spec\x12\x16\n" +
	"\x06sample\x18\x05 \x01(\tR\x06sample\"L\n" +
	"\bCronHour\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12,\n" +
	"\x04jobs\x18\x02 \x03(\v2\x18.fatima.opm.v2.CronEntryR\x04jobs\"\x89\x01\n" +
	"\vCronCatalog\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12,\n" +
	"\x04jobs\x18\x02 \x03(\v2\x18.fatima.opm.v2.CronEntryR\x04jobs\x12-\n" +
	"\x05hours\x18\x03 \x03(\v2\x17.fatima.opm.v2.CronHourR\x05hours\"v\n" +
	"\vCronRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aprocess\x18\x02 \x01(\tR\aprocess\x12\x10\n" +
	"\x03job\x18\x03 \x01(\tR\x03job\x12\x1c\n" +
	"\targuments\x18\x04 \x01(\tR\targuments\"\xf3\x01\n" +
	"\x10ControlOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12,\n" +
	"\x06events\x18\x06 \x03(\v2\x14.fatima.opm.v2.EventR\x06events\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt\"*\n" +
	"\fProcessQuery\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\"\x8b\x02\n" +
	"\fProcessEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\tR\x03pid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\tR\x06memory\x12\x0e\n" +
	"\x02fd\x18\a \x01(\tR\x02fd\x12\x18\n" +
	"\athreads\x18\b \x01(\tR\athreads\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\tR\tstartedAt\x12\x0e\n" +
	"\x02ic\x18\n" +
	" \x01(\tR\x02ic\x12\x14\n" +
	"\x05index\x18\v \x01(\x05R\x05index\x12\x10\n" +
	"\x03opm\x18\f \x01(\bR\x03opm\"\xf7\x01\n" +
	"\x0eProcessCatalog\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\tha_status\x18\x04 \x01(\x05R\bhaStatus\x12\x1b\n" +
	"\tps_status\x18\x05 \x01(\x05R\bpsStatus\x129\n" +
	"\tprocesses\x18\x06 \x03(\v2\x1b.fatima.opm.v2.ProcessEntryR\tprocesses\x12\x1f\n" +
	"\vobserved_at\x18\a \x01(\x03R\n" +
	"observedAt\"M\n" +
	"\x0eProcessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tprocesses\x18\x02 \x03(\tR\tprocesses\"J\n" +
	"\rRegistryQuery\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\"2\n" +
	"\fProcessGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9b\x01\n" +
	"\x0fRegistryCatalog\x127\n" +
	"\acatalog\x18\x01 \x01(\v2\x1d.fatima.opm.v2.ProcessCatalogR\acatalog\x123\n" +
	"\x06groups\x18\x02 \x03(\v2\x1b.fatima.opm.v2.ProcessGroupR\x06groups\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\"\xc4\x01\n" +
	"\x0fRegistryRequest\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\aprocess\x18\x04 \x01(\tR\aprocess\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12+\n" +
	"\x11expected_revision\x18\x06 \x01(\tR\x10expectedRevision\"b\n" +
	"\fRegistryPlan\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.fatima.opm.v2.RegistryRequestR\arequest\x12\x18\n" +
	"\aeffects\x18\x02 \x03(\tR\aeffects\"G\n" +
	"\x16RegistryOperationQuery\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"g\n" +
	"\rLogLevelEntry\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x10\n" +
	"\x03opm\x18\x04 \x01(\bR\x03opm\"h\n" +
	"\x0fLogLevelCatalog\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x126\n" +
	"\aentries\x18\x02 \x03(\v2\x1c.fatima.opm.v2.LogLevelEntryR\aentries\"A\n" +
	"\x0fLogLevelRequest\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x80\x02\n" +
	"\x10DeploymentRecord\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1f\n" +
	"\vdeployed_at\x18\x03 \x01(\x03R\n" +
	"deployedAt\x12\x1d\n" +
	"\n" +
	"build_user\x18\x04 \x01(\tR\tbuildUser\x12\x1d\n" +
	"\n" +
	"build_time\x18\x05 \x01(\tR\tbuildTime\x12\x1d\n" +
	"\n" +
	"git_branch\x18\x06 \x01(\tR\tgitBranch\x12\x1d\n" +
	"\n" +
	"git_commit\x18\a \x01(\tR\tgitCommit\x12\x1f\n" +
	"\vgit_message\x18\b \x01(\tR\n" +
	"gitMessage\"(\n" +
	"\fHistoryQuery\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\"g\n" +
	"\vHistoryList\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x129\n" +
	"\arecords\x18\x02 \x03(\v2\x1f.fatima.opm.v2.DeploymentRecordR\arecords2H\n" +
	"\aRouting\x12=\n" +
	"\aResolve\x12\x1b.fatima.opm.v2.PackageQuery\x1a\x15.fatima.opm.v2.Target2\x8f\x01\n" +
	"\x10PackageInventory\x12;\n" +
	"\x04List\x12\x14.fatima.opm.v2.Empty\x1a\x1d.fatima.opm.v2.PackageCatalog\x12>\n" +
	"\x05Watch\x12\x14.fatima.opm.v2.Empty\x1a\x1d.fatima.opm.v2.PackageCatalog0\x012\x9f\x02\n" +
	"\vCronControl\x128\n" +
	"\x04List\x12\x14.fatima.opm.v2.Empty\x1a\x1a.fatima.opm.v2.CronCatalog\x12D\n" +
	"\x05Rerun\x12\x1a.fatima.opm.v2.CronRequest\x1a\x1f.fatima.opm.v2.ControlOperation\x12E\n" +
	"\x03Get\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x1f.fatima.opm.v2.ControlOperation\x12I\n" +
	"\x05Watch\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x1f.fatima.opm.v2.ControlOperation0\x012\xc8\x03\n" +
	"\x0eProcessControl\x12E\n" +
	"\aCatalog\x12\x1b.fatima.opm.v2.ProcessQuery\x1a\x1d.fatima.opm.v2.ProcessCatalog\x12L\n" +
	"\fWatchCatalog\x12\x1b.fatima.opm.v2.ProcessQuery\x1a\x1d.fatima.opm.v2.ProcessCatalog0\x01\x12F\n" +
	"\x04Stop\x12\x1d.fatima.opm.v2.ProcessRequest\x1a\x1f.fatima.opm.v2.ControlOperation\x12G\n" +
	"\x05Start\x12\x1d.fatima.opm.v2.ProcessRequest\x1a\x1f.fatima.opm.v2.ControlOperation\x12E\n" +
	"\x03Get\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x1f.fatima.opm.v2.ControlOperation\x12I\n" +
	"\x05Watch\x12\x1d.fatima.opm.v2.OperationQuery\x1a\x1f.fatima.opm.v2.ControlOperation0\x012\x8e\x03\n" +
	"\x0fProcessRegistry\x12G\n" +
	"\aCatalog\x12\x1c.fatima.opm.v2.RegistryQuery\x1a\x1e.fatima.opm.v2.RegistryCatalog\x12F\n" +
	"\aPreview\x12\x1e.fatima.opm.v2.RegistryRequest\x1a\x1b.fatima.opm.v2.RegistryPlan\x12H\n" +
	"\x05Apply\x12\x1e.fatima.opm.v2.RegistryRequest\x1a\x1f.fatima.opm.v2.ControlOperation\x12M\n" +
	"\x03Get\x12%.fatima.opm.v2.RegistryOperationQuery\x1a\x1f.fatima.opm.v2.ControlOperation\x12Q\n" +
	"\x05Watch\x12%.fatima.opm.v2.RegistryOperationQuery\x1a\x1f.fatima.opm.v2.ControlOperation0\x012\x94\x01\n" +
	"\x0fLogLevelControl\x12<\n" +
	"\x04List\x12\x14.fatima.opm.v2.Empty\x1a\x1e.fatima.opm.v2.LogLevelCatalog\x12C\n" +
	"\x03Set\x12\x1e.fatima.opm.v2.LogLevelRequest\x1a\x1c.fatima.opm.v2.LogLevelEntry2T\n" +
	"\x11DeploymentHistory\x12?\n" +
	"\x04List\x12\x1b.fatima.opm.v2.HistoryQuery\x1a\x1a.fatima.opm.v2.HistoryListB)Z'github.com/fatima-go/fatima-opm/api;apib\x06proto3"

var (
	file_api_operations_proto_rawDescOnce sync.Once
	file_api_operations_proto_rawDescData []byte
)

func file_api_operations_proto_rawDescGZIP() []byte {
	file_api_operations_proto_rawDescOnce.Do(func() {
		file_api_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_operations_proto_rawDesc), len(file_api_operations_proto_rawDesc)))
	})
	return file_api_operations_proto_rawDescData
}

var file_api_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_operations_proto_goTypes = []any{
	(*PackageQuery)(nil),           // 0: fatima.opm.v2.PackageQuery
	(*PackageEntry)(nil),           // 1: fatima.opm.v2.PackageEntry
	(*PackageCatalog)(nil),         // 2: fatima.opm.v2.PackageCatalog
	(*CronEntry)(nil),              // 3: fatima.opm.v2.CronEntry
	(*CronHour)(nil),               // 4: fatima.opm.v2.CronHour
	(*CronCatalog)(nil),            // 5: fatima.opm.v2.CronCatalog
	(*CronRequest)(nil),            // 6: fatima.opm.v2.CronRequest
	(*ControlOperation)(nil),       // 7: fatima.opm.v2.ControlOperation
	(*ProcessQuery)(nil),           // 8: fatima.opm.v2.ProcessQuery
	(*ProcessEntry)(nil),           // 9: fatima.opm.v2.ProcessEntry
	(*ProcessCatalog)(nil),         // 10: fatima.opm.v2.ProcessCatalog
	(*ProcessRequest)(nil),         // 11: fatima.opm.v2.ProcessRequest
	(*RegistryQuery)(nil),          // 12: fatima.opm.v2.RegistryQuery
	(*ProcessGroup)(nil),           // 13: fatima.opm.v2.ProcessGroup
	(*RegistryCatalog)(nil),        // 14: fatima.opm.v2.RegistryCatalog
	(*RegistryRequest)(nil),        // 15: fatima.opm.v2.RegistryRequest
	(*RegistryPlan)(nil),           // 16: fatima.opm.v2.RegistryPlan
	(*RegistryOperationQuery)(nil), // 17: fatima.opm.v2.RegistryOperationQuery
	(*LogLevelEntry)(nil),          // 18: fatima.opm.v2.LogLevelEntry
	(*LogLevelCatalog)(nil),        // 19: fatima.opm.v2.LogLevelCatalog
	(*LogLevelRequest)(nil),        // 20: fatima.opm.v2.LogLevelRequest
	(*DeploymentRecord)(nil),       // 21: fatima.opm.v2.DeploymentRecord
	(*HistoryQuery)(nil),           // 22: fatima.opm.v2.HistoryQuery
	(*HistoryList)(nil),            // 23: fatima.opm.v2.HistoryList
	(*Target)(nil),                 // 24: fatima.opm.v2.Target
	(*Event)(nil),                  // 25: fatima.opm.v2.Event
	(*Empty)(nil),                  // 26: fatima.opm.v2.Empty
	(*OperationQuery)(nil),         // 27: fatima.opm.v2.OperationQuery
}
var file_api_operations_proto_depIdxs = []int32{
	24, // 0: fatima.opm.v2.PackageEntry.target:type_name -> fatima.opm.v2.Target
	1,  // 1: fatima.opm.v2.PackageCatalog.packages:type_name -> fatima.opm.v2.PackageEntry
	3,  // 2: fatima.opm.v2.CronHour.jobs:type_name -> fatima.opm.v2.CronEntry
	3,  // 3: fatima.opm.v2.CronCatalog.jobs:type_name -> fatima.opm.v2.CronEntry
	4,  // 4: fatima.opm.v2.CronCatalog.hours:type_name -> fatima.opm.v2.CronHour
	25, // 5: fatima.opm.v2.ControlOperation.events:type_name -> fatima.opm.v2.Event
	9,  // 6: fatima.opm.v2.ProcessCatalog.processes:type_name -> fatima.opm.v2.ProcessEntry
	10, // 7: fatima.opm.v2.RegistryCatalog.catalog:type_name -> fatima.opm.v2.ProcessCatalog
	13, // 8: fatima.opm.v2.RegistryCatalog.groups:type_name -> fatima.opm.v2.ProcessGroup
	15, // 9: fatima.opm.v2.RegistryPlan.request:type_name -> fatima.opm.v2.RegistryRequest
	18, // 10: fatima.opm.v2.LogLevelCatalog.entries:type_name -> fatima.opm.v2.LogLevelEntry
	21, // 11: fatima.opm.v2.HistoryList.records:type_name -> fatima.opm.v2.DeploymentRecord
	0,  // 12: fatima.opm.v2.Routing.Resolve:input_type -> fatima.opm.v2.PackageQuery
	26, // 13: fatima.opm.v2.PackageInventory.List:input_type -> fatima.opm.v2.Empty
	26, // 14: fatima.opm.v2.PackageInventory.Watch:input_type -> fatima.opm.v2.Empty
	26, // 15: fatima.opm.v2.CronControl.List:input_type -> fatima.opm.v2.Empty
	6,  // 16: fatima.opm.v2.CronControl.Rerun:input_type -> fatima.opm.v2.CronRequest
	27, // 17: fatima.opm.v2.CronControl.Get:input_type -> fatima.opm.v2.OperationQuery
	27, // 18: fatima.opm.v2.CronControl.Watch:input_type -> fatima.opm.v2.OperationQuery
	8,  // 19: fatima.opm.v2.ProcessControl.Catalog:input_type -> fatima.opm.v2.ProcessQuery
	8,  // 20: fatima.opm.v2.ProcessControl.WatchCatalog:input_type -> fatima.opm.v2.ProcessQuery
	11, // 21: fatima.opm.v2.ProcessControl.Stop:input_type -> fatima.opm.v2.ProcessRequest
	11, // 22: fatima.opm.v2.ProcessControl.Start:input_type -> fatima.opm.v2.ProcessRequest
	27, // 23: fatima.opm.v2.ProcessControl.Get:input_type -> fatima.opm.v2.OperationQuery
	27, // 24: fatima.opm.v2.ProcessControl.Watch:input_type -> fatima.opm.v2.OperationQuery
	12, // 25: fatima.opm.v2.ProcessRegistry.Catalog:input_type -> fatima.opm.v2.RegistryQuery
	15, // 26: fatima.opm.v2.ProcessRegistry.Preview:input_type -> fatima.opm.v2.RegistryRequest
	15, // 27: fatima.opm.v2.ProcessRegistry.Apply:input_type -> fatima.opm.v2.RegistryRequest
	17, // 28: fatima.opm.v2.ProcessRegistry.Get:input_type -> fatima.opm.v2.RegistryOperationQuery
	17, // 29: fatima.opm.v2.ProcessRegistry.Watch:input_type -> fatima.opm.v2.RegistryOperationQuery
	26, // 30: fatima.opm.v2.LogLevelControl.List:input_type -> fatima.opm.v2.Empty
	20, // 31: fatima.opm.v2.LogLevelControl.Set:input_type -> fatima.opm.v2.LogLevelRequest
	22, // 32: fatima.opm.v2.DeploymentHistory.List:input_type -> fatima.opm.v2.HistoryQuery
	24, // 33: fatima.opm.v2.Routing.Resolve:output_type -> fatima.opm.v2.Target
	2,  // 34: fatima.opm.v2.PackageInventory.List:output_type -> fatima.opm.v2.PackageCatalog
	2,  // 35: fatima.opm.v2.PackageInventory.Watch:output_type -> fatima.opm.v2.PackageCatalog
	5,  // 36: fatima.opm.v2.CronControl.List:output_type -> fatima.opm.v2.CronCatalog
	7,  // 37: fatima.opm.v2.CronControl.Rerun:output_type -> fatima.opm.v2.ControlOperation
	7,  // 38: fatima.opm.v2.CronControl.Get:output_type -> fatima.opm.v2.ControlOperation
	7,  // 39: fatima.opm.v2.CronControl.Watch:output_type -> fatima.opm.v2.ControlOperation
	10, // 40: fatima.opm.v2.ProcessControl.Catalog:output_type -> fatima.opm.v2.ProcessCatalog
	10, // 41: fatima.opm.v2.ProcessControl.WatchCatalog:output_type -> fatima.opm.v2.ProcessCatalog
	7,  // 42: fatima.opm.v2.ProcessControl.Stop:output_type -> fatima.opm.v2.ControlOperation
	7,  // 43: fatima.opm.v2.ProcessControl.Start:output_type -> fatima.opm.v2.ControlOperation
	7,  // 44: fatima.opm.v2.ProcessControl.Get:output_type -> fatima.opm.v2.ControlOperation
	7,  // 45: fatima.opm.v2.ProcessControl.Watch:output_type -> fatima.opm.v2.ControlOperation
	14, // 46: fatima.opm.v2.ProcessRegistry.Catalog:output_type -> fatima.opm.v2.RegistryCatalog
	16, // 47: fatima.opm.v2.ProcessRegistry.Preview:output_type -> fatima.opm.v2.RegistryPlan
	7,  // 48: fatima.opm.v2.ProcessRegistry.Apply:output_type -> fatima.opm.v2.ControlOperation
	7,  // 49: fatima.opm.v2.ProcessRegistry.Get:output_type -> fatima.opm.v2.ControlOperation
	7,  // 50: fatima.opm.v2.ProcessRegistry.Watch:output_type -> fatima.opm.v2.ControlOperation
	19, // 51: fatima.opm.v2.LogLevelControl.List:output_type -> fatima.opm.v2.LogLevelCatalog
	18, // 52: fatima.opm.v2.LogLevelControl.Set:output_type -> fatima.opm.v2.LogLevelEntry
	23, // 53: fatima.opm.v2.DeploymentHistory.List:output_type -> fatima.opm.v2.HistoryList
	33, // [33:54] is the sub-list for method output_type
	12, // [12:33] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_operations_proto_init() }
func file_api_operations_proto_init() {
	if File_api_operations_proto != nil {
		return
	}
	file_api_control_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_operations_proto_rawDesc), len(file_api_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_api_operations_proto_goTypes,
		DependencyIndexes: file_api_operations_proto_depIdxs,
		MessageInfos:      file_api_operations_proto_msgTypes,
	}.Build()
	File_api_operations_proto = out.File
	file_api_operations_proto_goTypes = nil
	file_api_operations_proto_depIdxs = nil
}
